// Decompiled with JetBrains decompiler
// Type: TaleWorlds.Core.BannerData
// Assembly: TaleWorlds.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 43F7B45C-9AE1-4715-A37B-2364840F62AF
// Assembly location: E:\SteamLibrary\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Core.dll

using System.Collections.Generic;
using TaleWorlds.Library;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.Core
{
  [SaveableClass(10003)]
  public class BannerData
  {
    public const float RotationPrecision = 0.00278f;
    [SaveableField(1)]
    public int MeshId;
    [SaveableField(2)]
    public int ColorId;
    [SaveableField(3)]
    public int ColorId2;
    [SaveableField(4)]
    public Vec2 Size;
    [SaveableField(5)]
    public Vec2 Position;
    [SaveableField(6)]
    public bool DrawStroke;
    [SaveableField(7)]
    public bool Mirror;
    [SaveableField(8)]
    public float RotationValue;

    public float Rotation => 6.283185f * this.RotationValue;

    public BannerData(
      int meshId,
      int colorId,
      int colorId2,
      Vec2 size,
      Vec2 position,
      bool drawStroke,
      bool mirror,
      float rotationValue)
    {
      this.MeshId = meshId;
      this.ColorId = colorId;
      this.ColorId2 = colorId2;
      this.Size = size;
      this.Position = position;
      this.DrawStroke = drawStroke;
      this.Mirror = mirror;
      this.RotationValue = rotationValue;
    }

    public BannerData(BannerData bannerData)
      : this(bannerData.MeshId, bannerData.ColorId, bannerData.ColorId2, bannerData.Size, bannerData.Position, bannerData.DrawStroke, bannerData.Mirror, bannerData.RotationValue)
    {
    }

    internal static void AutoGeneratedStaticCollectObjectsBannerData(
      object o,
      List<object> collectedObjects)
    {
      ((BannerData) o).AutoGeneratedInstanceCollectObjects(collectedObjects);
    }

    protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
    {
    }

    internal static object AutoGeneratedGetMemberValueMeshId(object o) => (object) ((BannerData) o).MeshId;

    internal static object AutoGeneratedGetMemberValueColorId(object o) => (object) ((BannerData) o).ColorId;

    internal static object AutoGeneratedGetMemberValueColorId2(object o) => (object) ((BannerData) o).ColorId2;

    internal static object AutoGeneratedGetMemberValueSize(object o) => (object) ((BannerData) o).Size;

    internal static object AutoGeneratedGetMemberValuePosition(object o) => (object) ((BannerData) o).Position;

    internal static object AutoGeneratedGetMemberValueDrawStroke(object o) => (object) ((BannerData) o).DrawStroke;

    internal static object AutoGeneratedGetMemberValueMirror(object o) => (object) ((BannerData) o).Mirror;

    internal static object AutoGeneratedGetMemberValueRotationValue(object o) => (object) ((BannerData) o).RotationValue;
  }
}
