// Decompiled with JetBrains decompiler
// Type: TaleWorlds.Core.CharacterSkills
// Assembly: TaleWorlds.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 43F7B45C-9AE1-4715-A37B-2364840F62AF
// Assembly location: E:\SteamLibrary\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Core.dll

using System;
using System.Collections.Generic;
using System.Xml;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.Core
{
  [SaveableClass(10004)]
  public class CharacterSkills : PropertyOwner<SkillObject>
  {
    public CharacterSkills(CharacterSkills propertyOwner)
      : base((PropertyOwner<SkillObject>) propertyOwner)
    {
    }

    public CharacterSkills()
    {
    }

    public override void Deserialize(MBObjectManager objectManager, XmlNode node)
    {
      this.Initialize();
      foreach (XmlNode childNode in node.ChildNodes)
      {
        if (childNode.NodeType != XmlNodeType.Comment)
        {
          XmlAttributeCollection attributes = childNode.Attributes;
          string objectName = attributes["id"].Value;
          string str = attributes["value"].Value;
          SkillObject attribute = Game.Current.ObjectManager.GetObject<SkillObject>(objectName);
          if (attribute != null)
          {
            int num = str != null ? Convert.ToInt32(str) : 1;
            this.SetPropertyValue(attribute, num);
          }
        }
      }
      foreach (XmlNode childNode in node.ChildNodes)
      {
        if (childNode.NodeType != XmlNodeType.Comment)
        {
          string objectName = childNode.Name;
          int num = 1;
          if (objectName == "skill")
          {
            objectName = (string) null;
            if (childNode.Attributes != null)
            {
              XmlAttribute attribute = childNode.Attributes["id"];
              if (attribute != null)
                objectName = attribute.InnerText;
            }
          }
          if (objectName != null)
          {
            SkillObject attribute1 = Game.Current.ObjectManager.GetObject<SkillObject>(objectName);
            if (attribute1 != null)
            {
              XmlAttribute attribute2 = childNode.Attributes["value"];
              if (attribute2 != null)
              {
                string str = attribute2.Value;
                num = str != null ? Convert.ToInt32(str) : 1;
              }
              this.SetPropertyValue(attribute1, num);
            }
          }
        }
      }
    }

    internal static void AutoGeneratedStaticCollectObjectsCharacterSkills(
      object o,
      List<object> collectedObjects)
    {
      ((MBObjectBase) o).AutoGeneratedInstanceCollectObjects(collectedObjects);
    }

    protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects) => base.AutoGeneratedInstanceCollectObjects(collectedObjects);
  }
}
