// Decompiled with JetBrains decompiler
// Type: TaleWorlds.Core.DefaultSkills
// Assembly: TaleWorlds.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 43F7B45C-9AE1-4715-A37B-2364840F62AF
// Assembly location: E:\SteamLibrary\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Core.dll

using System.Collections.Generic;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.Core
{
  [SaveableClass(20508)]
  public class DefaultSkills
  {
    public const int MaxAssumedValue = 250;

    internal static void AutoGeneratedStaticCollectObjectsDefaultSkills(
      object o,
      List<object> collectedObjects)
    {
      ((DefaultSkills) o).AutoGeneratedInstanceCollectObjects(collectedObjects);
    }

    protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
    {
    }

    internal static DefaultSkills Instance => Game.Current.DefaultSkills;

    public static SkillObject OneHanded => DefaultSkills.Instance.SkillOneHanded;

    public static SkillObject TwoHanded => DefaultSkills.Instance.SkillTwoHanded;

    public static SkillObject Polearm => DefaultSkills.Instance.SkillPolearm;

    public static SkillObject Bow => DefaultSkills.Instance.SkillBow;

    public static SkillObject Crossbow => DefaultSkills.Instance.SkillCrossbow;

    public static SkillObject Throwing => DefaultSkills.Instance.SkillThrowing;

    public static SkillObject Riding => DefaultSkills.Instance.SkillRiding;

    public static SkillObject Athletics => DefaultSkills.Instance.SkillAthletics;

    public static SkillObject Crafting => DefaultSkills.Instance.SkillCrafting;

    public static SkillObject Tactics => DefaultSkills.Instance.SkillTactics;

    public static SkillObject Scouting => DefaultSkills.Instance.SkillScouting;

    public static SkillObject Roguery => DefaultSkills.Instance.SkillRoguery;

    public static SkillObject Charm => DefaultSkills.Instance.SkillCharm;

    public static SkillObject Leadership => DefaultSkills.Instance.SkillLeadership;

    public static SkillObject Trade => DefaultSkills.Instance.SkillTrade;

    public static SkillObject Steward => DefaultSkills.Instance.SkillSteward;

    public static SkillObject Medicine => DefaultSkills.Instance.SkillMedicine;

    public static SkillObject Engineering => DefaultSkills.Instance.SkillEngineering;

    internal SkillObject SkillOneHanded { get; private set; }

    internal SkillObject SkillTwoHanded { get; private set; }

    internal SkillObject SkillPolearm { get; private set; }

    internal SkillObject SkillBow { get; private set; }

    internal SkillObject SkillCrossbow { get; private set; }

    internal SkillObject SkillThrowing { get; private set; }

    internal SkillObject SkillRiding { get; private set; }

    internal SkillObject SkillAthletics { get; private set; }

    internal SkillObject SkillCrafting { get; private set; }

    internal SkillObject SkillTactics { get; private set; }

    internal SkillObject SkillScouting { get; private set; }

    internal SkillObject SkillRoguery { get; private set; }

    internal SkillObject SkillCharm { get; private set; }

    internal SkillObject SkillTrade { get; private set; }

    internal SkillObject SkillSteward { get; private set; }

    internal SkillObject SkillLeadership { get; private set; }

    internal SkillObject SkillMedicine { get; private set; }

    internal SkillObject SkillEngineering { get; private set; }

    public static IEnumerable<SkillObject> GetAllSkills()
    {
      yield return DefaultSkills.OneHanded;
      yield return DefaultSkills.TwoHanded;
      yield return DefaultSkills.Polearm;
      yield return DefaultSkills.Bow;
      yield return DefaultSkills.Crossbow;
      yield return DefaultSkills.Throwing;
      yield return DefaultSkills.Riding;
      yield return DefaultSkills.Athletics;
      yield return DefaultSkills.Crafting;
      yield return DefaultSkills.Tactics;
      yield return DefaultSkills.Scouting;
      yield return DefaultSkills.Roguery;
      yield return DefaultSkills.Charm;
      yield return DefaultSkills.Trade;
      yield return DefaultSkills.Steward;
      yield return DefaultSkills.Leadership;
      yield return DefaultSkills.Medicine;
      yield return DefaultSkills.Engineering;
    }

    public DefaultSkills(Game game) => this.RegisterAll(game);

    private void InitializeAll()
    {
      this.SkillOneHanded.Initialize(new TextObject("{=PiHpR4QL}One Handed"), new TextObject("{=yEkSSqIm}Mastery of fighting with one-handed weapons either with a shield or without."), SkillObject.SkillTypeEnum.Personal).SetAttribute(CharacterAttributes.Vigor);
      this.SkillTwoHanded.Initialize(new TextObject("{=t78atYqH}Two Handed"), new TextObject("{=eoLbkhsY}Mastery of fighting with two-handed weapons of average length such as bigger axes and swords."), SkillObject.SkillTypeEnum.Personal).SetAttribute(CharacterAttributes.Vigor);
      this.SkillPolearm.Initialize(new TextObject("{=haax8kMa}Polearm"), new TextObject("{=iKmXX7i3}Mastery of the spear, lance, staff and other polearms, both one-handed and two-handed."), SkillObject.SkillTypeEnum.Personal).SetAttribute(CharacterAttributes.Vigor);
      this.SkillBow.Initialize(new TextObject("{=5rj7xQE4}Bow"), new TextObject("{=FLf5J3su}Familarity with bows and physical conditioning to shoot with them effectively."), SkillObject.SkillTypeEnum.Personal).SetAttribute(CharacterAttributes.Control);
      this.SkillCrossbow.Initialize(new TextObject("{=TTWL7RLe}Crossbow"), new TextObject("{=haV3nLYA}Knowledge of operating and maintaining crossbows."), SkillObject.SkillTypeEnum.Personal).SetAttribute(CharacterAttributes.Control);
      this.SkillThrowing.Initialize(new TextObject("{=2wclahIJ}Throwing"), new TextObject("{=NwTpATW5}Mastery of throwing projectiles accurately and with power."), SkillObject.SkillTypeEnum.Personal).SetAttribute(CharacterAttributes.Control);
      this.SkillRiding.Initialize(new TextObject("{=p9i3zRm9}Riding"), new TextObject("{=H9Zamrao}The ability to control a horse, to keep your balance when it moves suddenly or unexpectedly, as well as general knowledge of horses, including their care and breeding."), SkillObject.SkillTypeEnum.Personal).SetAttribute(CharacterAttributes.Endurance);
      this.SkillAthletics.Initialize(new TextObject("{=skZS2UlW}Athletics"), new TextObject("{=bVD9j0wI}Physical fitness, speed and balance."), SkillObject.SkillTypeEnum.Personal).SetAttribute(CharacterAttributes.Endurance);
      this.SkillCrafting.Initialize(new TextObject("{=smithingskill}Smithing"), new TextObject("{=xWbkjccP}The knowledge of how to forge metal, match handle to blade, turn poles, sew scales, and other skills useful in the assembly of weapons and armor"), SkillObject.SkillTypeEnum.Personal).SetAttribute(CharacterAttributes.Endurance);
      this.SkillScouting.Initialize(new TextObject("{=LJ6Krlbr}Scouting"), new TextObject("{=kmBxaJZd}Knowledge of how to scan the wilderness for life. You can follow tracks, spot movement in the undergrowth, and spot an enemy across the valley from a flash of light on spearpoints or a dustcloud."), SkillObject.SkillTypeEnum.Party).SetAttribute(CharacterAttributes.Cunning);
      this.SkillTactics.Initialize(new TextObject("{=m8o51fc7}Tactics"), new TextObject("{=FQOFDrAu}Your judgment of how troops will perform in contact. This allows you to make a good prediction of when an unorthodox tactic will work, and when it won't."), SkillObject.SkillTypeEnum.Personal).SetAttribute(CharacterAttributes.Cunning);
      this.SkillRoguery.Initialize(new TextObject("{=V0ZMJ0PX}Roguery"), new TextObject("{=81YLbLok}Experience with the darker side of human life. You can tell when a guard wants a bribe, you know how to intimidate someone, and have a good sense of what you can and can't get away with."), SkillObject.SkillTypeEnum.Personal).SetAttribute(CharacterAttributes.Cunning);
      this.SkillCharm.Initialize(new TextObject("{=EGeY1gfs}Charm"), new TextObject("{=VajIVjkc}The ability to make a person like and trust you. You can make a good guess at people's motivations and the kinds of arguments to which they'll respond."), SkillObject.SkillTypeEnum.Personal).SetAttribute(CharacterAttributes.Social);
      this.SkillLeadership.Initialize(new TextObject("{=HsLfmEmb}Leadership"), new TextObject("{=97EmbcHQ}The ability to inspire. You can fill individuals with confidence and stir up enthusiasm and courage in larger groups."), SkillObject.SkillTypeEnum.Personal).SetAttribute(CharacterAttributes.Social);
      this.SkillTrade.Initialize(new TextObject("{=GmcgoiGy}Trade"), new TextObject("{=lsJMCkZy}Familiarity with the most common goods in the marketplace and their prices, as well as the ability to spot defective goods or tell if you've been shortchanged in quantity"), SkillObject.SkillTypeEnum.Party).SetAttribute(CharacterAttributes.Social);
      this.SkillSteward.Initialize(new TextObject("{=stewardskill}Steward"), new TextObject("{=2K0iVRkW}Ability to organize a group and manage logistics. This helps you to run an estate or administer a town, and can increase the size of a party that you lead or in which you serve as quartermaster."), SkillObject.SkillTypeEnum.Party).SetAttribute(CharacterAttributes.Intelligence);
      this.SkillMedicine.Initialize(new TextObject("{=JKH59XNp}Medicine"), new TextObject("{=igg5sEh3}Knowledge of how to staunch bleeding, to set broken bones, to remove embedded weapons and clean wounds to prevent infection, and to apply poultices to relieve pain and soothe inflammation."), SkillObject.SkillTypeEnum.Party).SetAttribute(CharacterAttributes.Intelligence);
      this.SkillEngineering.Initialize(new TextObject("{=engineeringskill}Engineering"), new TextObject("{=hbaMnpVR}Knowledge of how to make things that can withstand powerful forces without collapsing. Useful for building both structures and the devices that knock them down."), SkillObject.SkillTypeEnum.Party).SetAttribute(CharacterAttributes.Intelligence);
    }

    private void RegisterAll(Game game)
    {
      this.SkillOneHanded = game.ObjectManager.RegisterPresumedObject<SkillObject>(new SkillObject("OneHanded"));
      this.SkillTwoHanded = game.ObjectManager.RegisterPresumedObject<SkillObject>(new SkillObject("TwoHanded"));
      this.SkillPolearm = game.ObjectManager.RegisterPresumedObject<SkillObject>(new SkillObject("Polearm"));
      this.SkillBow = game.ObjectManager.RegisterPresumedObject<SkillObject>(new SkillObject("Bow"));
      this.SkillThrowing = game.ObjectManager.RegisterPresumedObject<SkillObject>(new SkillObject("Throwing"));
      this.SkillCrossbow = game.ObjectManager.RegisterPresumedObject<SkillObject>(new SkillObject("Crossbow"));
      this.SkillRiding = game.ObjectManager.RegisterPresumedObject<SkillObject>(new SkillObject("Riding"));
      this.SkillAthletics = game.ObjectManager.RegisterPresumedObject<SkillObject>(new SkillObject("Athletics"));
      this.SkillCrafting = game.ObjectManager.RegisterPresumedObject<SkillObject>(new SkillObject("Crafting"));
      this.SkillTactics = game.ObjectManager.RegisterPresumedObject<SkillObject>(new SkillObject("Tactics"));
      this.SkillScouting = game.ObjectManager.RegisterPresumedObject<SkillObject>(new SkillObject("Scouting"));
      this.SkillRoguery = game.ObjectManager.RegisterPresumedObject<SkillObject>(new SkillObject("Roguery"));
      this.SkillCharm = game.ObjectManager.RegisterPresumedObject<SkillObject>(new SkillObject("Charm"));
      this.SkillTrade = game.ObjectManager.RegisterPresumedObject<SkillObject>(new SkillObject("Trade"));
      this.SkillSteward = game.ObjectManager.RegisterPresumedObject<SkillObject>(new SkillObject("Steward"));
      this.SkillMedicine = game.ObjectManager.RegisterPresumedObject<SkillObject>(new SkillObject("Medicine"));
      this.SkillEngineering = game.ObjectManager.RegisterPresumedObject<SkillObject>(new SkillObject("Engineering"));
      this.SkillLeadership = game.ObjectManager.RegisterPresumedObject<SkillObject>(new SkillObject("Leadership"));
      this.InitializeAll();
    }
  }
}
