// Decompiled with JetBrains decompiler
// Type: TaleWorlds.Core.DefaultItemCategories
// Assembly: TaleWorlds.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 43F7B45C-9AE1-4715-A37B-2364840F62AF
// Assembly location: E:\SteamLibrary\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Core.dll

using System.Collections.Generic;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.Core
{
  [SaveableClass(10006)]
  public class DefaultItemCategories
  {
    private readonly ItemCategory[] _itemCategories;

    internal static void AutoGeneratedStaticCollectObjectsDefaultItemCategories(
      object o,
      List<object> collectedObjects)
    {
      ((DefaultItemCategories) o).AutoGeneratedInstanceCollectObjects(collectedObjects);
    }

    protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
    {
    }

    internal static DefaultItemCategories Instance => Game.Current.DefaultItemCategories;

    public static IReadOnlyList<ItemCategory> All => (IReadOnlyList<ItemCategory>) DefaultItemCategories.Instance._itemCategories;

    public static ItemCategory Grain => DefaultItemCategories.Instance.ItemCategoryGrain;

    public static ItemCategory Wood => DefaultItemCategories.Instance.ItemCategoryWood;

    public static ItemCategory Meat => DefaultItemCategories.Instance.ItemCategoryMeat;

    public static ItemCategory Wool => DefaultItemCategories.Instance.ItemCategoryWool;

    public static ItemCategory Cheese => DefaultItemCategories.Instance.ItemCategoryCheese;

    public static ItemCategory Iron => DefaultItemCategories.Instance.ItemCategoryIron;

    public static ItemCategory Salt => DefaultItemCategories.Instance.ItemCategorySalt;

    public static ItemCategory Silver => DefaultItemCategories.Instance.ItemCategorySilver;

    public static ItemCategory Cotton => DefaultItemCategories.Instance.ItemCategoryCotton;

    public static ItemCategory Fish => DefaultItemCategories.Instance.ItemCategoryFish;

    public static ItemCategory Flax => DefaultItemCategories.Instance.ItemCategoryFlax;

    public static ItemCategory Grape => DefaultItemCategories.Instance.ItemCategoryGrape;

    public static ItemCategory Hides => DefaultItemCategories.Instance.ItemCategoryHides;

    public static ItemCategory Clay => DefaultItemCategories.Instance.ItemCategoryClay;

    public static ItemCategory DateFruit => DefaultItemCategories.Instance.ItemCategoryDateFruit;

    public static ItemCategory Olives => DefaultItemCategories.Instance.ItemCategoryOlives;

    public static ItemCategory Beer => DefaultItemCategories.Instance.ItemCategoryBeer;

    public static ItemCategory Wine => DefaultItemCategories.Instance.ItemCategoryWine;

    public static ItemCategory Oil => DefaultItemCategories.Instance.ItemCategoryOil;

    public static ItemCategory Tools => DefaultItemCategories.Instance.ItemCategoryTools;

    public static ItemCategory Pottery => DefaultItemCategories.Instance.ItemCategoryPottery;

    public static ItemCategory Cloth => DefaultItemCategories.Instance.ItemCategoryCloth;

    public static ItemCategory Linen => DefaultItemCategories.Instance.ItemCategoryLinen;

    public static ItemCategory Leather => DefaultItemCategories.Instance.ItemCategoryLeather;

    public static ItemCategory Velvet => DefaultItemCategories.Instance.ItemCategoryVelvet;

    public static ItemCategory Sheep => DefaultItemCategories.Instance.ItemCategorySheep;

    public static ItemCategory Cow => DefaultItemCategories.Instance.ItemCategoryCow;

    public static ItemCategory Hog => DefaultItemCategories.Instance.ItemCategoryHog;

    public static ItemCategory Horse => DefaultItemCategories.Instance.ItemCategoryHorse;

    public static ItemCategory WarHorse => DefaultItemCategories.Instance.ItemCategoryWarHorse;

    public static ItemCategory Butter => DefaultItemCategories.Instance.ItemCategoryButter;

    public static ItemCategory Fur => DefaultItemCategories.Instance.ItemCategoryFur;

    public static ItemCategory Jewelry => DefaultItemCategories.Instance.ItemCategoryJewelry;

    public static ItemCategory PackAnimal => DefaultItemCategories.Instance.ItemCategoryPackAnimal;

    public static ItemCategory MeleeWeapons1 => DefaultItemCategories.Instance.ItemCategoryMeleeWeapons1;

    public static ItemCategory MeleeWeapons2 => DefaultItemCategories.Instance.ItemCategoryMeleeWeapons2;

    public static ItemCategory MeleeWeapons3 => DefaultItemCategories.Instance.ItemCategoryMeleeWeapons3;

    public static ItemCategory MeleeWeapons4 => DefaultItemCategories.Instance.ItemCategoryMeleeWeapons4;

    public static ItemCategory MeleeWeapons5 => DefaultItemCategories.Instance.ItemCategoryMeleeWeapons5;

    public static ItemCategory RangedWeapons1 => DefaultItemCategories.Instance.ItemCategoryRangedWeapons1;

    public static ItemCategory RangedWeapons2 => DefaultItemCategories.Instance.ItemCategoryRangedWeapons2;

    public static ItemCategory RangedWeapons3 => DefaultItemCategories.Instance.ItemCategoryRangedWeapons3;

    public static ItemCategory RangedWeapons4 => DefaultItemCategories.Instance.ItemCategoryRangedWeapons4;

    public static ItemCategory RangedWeapons5 => DefaultItemCategories.Instance.ItemCategoryRangedWeapons5;

    public static ItemCategory Shield1 => DefaultItemCategories.Instance.ItemCategoryShield;

    public static ItemCategory Shield2 => DefaultItemCategories.Instance.ItemCategoryShield2;

    public static ItemCategory Shield3 => DefaultItemCategories.Instance.ItemCategoryShield3;

    public static ItemCategory Shield4 => DefaultItemCategories.Instance.ItemCategoryShield4;

    public static ItemCategory Shield5 => DefaultItemCategories.Instance.ItemCategoryShield5;

    public static ItemCategory Garment => DefaultItemCategories.Instance.ItemCategoryGarment;

    public static ItemCategory LightArmor => DefaultItemCategories.Instance.ItemCategoryLightArmor;

    public static ItemCategory MediumArmor => DefaultItemCategories.Instance.ItemCategoryMediumArmor;

    public static ItemCategory HeavyArmor => DefaultItemCategories.Instance.ItemCategoryHeavyArmor;

    public static ItemCategory UltraArmor => DefaultItemCategories.Instance.ItemCategoryUltraArmor;

    public static ItemCategory SiegeWeapon => DefaultItemCategories.Instance.ItemCategorySiegeWeapon;

    public static ItemCategory HorseEquipment => DefaultItemCategories.Instance.ItemCategoryHorseEquipment;

    public static ItemCategory HorseEquipment2 => DefaultItemCategories.Instance.ItemCategoryHorseEquipment2;

    public static ItemCategory HorseEquipment3 => DefaultItemCategories.Instance.ItemCategoryHorseEquipment3;

    public static ItemCategory HorseEquipment4 => DefaultItemCategories.Instance.ItemCategoryHorseEquipment4;

    public static ItemCategory HorseEquipment5 => DefaultItemCategories.Instance.ItemCategoryHorseEquipment5;

    public static ItemCategory Arrows => DefaultItemCategories.Instance.ItemCategoryArrows;

    public static ItemCategory Unassigned => DefaultItemCategories.Instance.ItemCategoryUnassigned;

    internal ItemCategory ItemCategoryGrain { get; private set; }

    internal ItemCategory ItemCategoryWood { get; private set; }

    internal ItemCategory ItemCategoryMeat { get; private set; }

    internal ItemCategory ItemCategoryWool { get; private set; }

    internal ItemCategory ItemCategoryCheese { get; private set; }

    internal ItemCategory ItemCategoryIron { get; private set; }

    internal ItemCategory ItemCategorySalt { get; private set; }

    internal ItemCategory ItemCategorySilver { get; private set; }

    internal ItemCategory ItemCategoryCotton { get; private set; }

    internal ItemCategory ItemCategoryFish { get; private set; }

    internal ItemCategory ItemCategoryFlax { get; private set; }

    internal ItemCategory ItemCategoryGrape { get; private set; }

    internal ItemCategory ItemCategoryHides { get; private set; }

    internal ItemCategory ItemCategoryClay { get; private set; }

    internal ItemCategory ItemCategoryDateFruit { get; private set; }

    internal ItemCategory ItemCategoryOlives { get; private set; }

    internal ItemCategory ItemCategoryBeer { get; private set; }

    internal ItemCategory ItemCategoryWine { get; private set; }

    internal ItemCategory ItemCategoryOil { get; private set; }

    public ItemCategory ItemCategoryTools { get; private set; }

    internal ItemCategory ItemCategoryPottery { get; private set; }

    internal ItemCategory ItemCategoryCloth { get; private set; }

    internal ItemCategory ItemCategoryLinen { get; private set; }

    internal ItemCategory ItemCategoryLeather { get; private set; }

    internal ItemCategory ItemCategoryVelvet { get; private set; }

    internal ItemCategory ItemCategorySheep { get; private set; }

    internal ItemCategory ItemCategoryCow { get; private set; }

    internal ItemCategory ItemCategoryHog { get; private set; }

    internal ItemCategory ItemCategoryHorse { get; private set; }

    internal ItemCategory ItemCategoryPackAnimal { get; private set; }

    internal ItemCategory ItemCategoryWarHorse { get; private set; }

    internal ItemCategory ItemCategoryMeleeWeapons1 { get; private set; }

    internal ItemCategory ItemCategoryMeleeWeapons2 { get; private set; }

    internal ItemCategory ItemCategoryMeleeWeapons3 { get; private set; }

    internal ItemCategory ItemCategoryMeleeWeapons4 { get; private set; }

    internal ItemCategory ItemCategoryMeleeWeapons5 { get; private set; }

    internal ItemCategory ItemCategoryRangedWeapons1 { get; private set; }

    internal ItemCategory ItemCategoryRangedWeapons2 { get; private set; }

    internal ItemCategory ItemCategoryRangedWeapons3 { get; private set; }

    internal ItemCategory ItemCategoryRangedWeapons4 { get; private set; }

    internal ItemCategory ItemCategoryRangedWeapons5 { get; private set; }

    internal ItemCategory ItemCategoryShield { get; private set; }

    internal ItemCategory ItemCategoryShield2 { get; private set; }

    internal ItemCategory ItemCategoryShield3 { get; private set; }

    internal ItemCategory ItemCategoryShield4 { get; private set; }

    internal ItemCategory ItemCategoryShield5 { get; private set; }

    internal ItemCategory ItemCategoryGarment { get; private set; }

    internal ItemCategory ItemCategoryLightArmor { get; private set; }

    internal ItemCategory ItemCategoryMediumArmor { get; private set; }

    internal ItemCategory ItemCategoryHeavyArmor { get; private set; }

    internal ItemCategory ItemCategoryUltraArmor { get; private set; }

    internal ItemCategory ItemCategorySiegeWeapon { get; private set; }

    internal ItemCategory ItemCategoryUnassigned { get; private set; }

    public ItemCategory ItemCategoryButter { get; private set; }

    public ItemCategory ItemCategoryFur { get; private set; }

    public ItemCategory ItemCategoryJewelry { get; private set; }

    public ItemCategory ItemCategoryHorseEquipment { get; private set; }

    public ItemCategory ItemCategoryHorseEquipment2 { get; private set; }

    public ItemCategory ItemCategoryHorseEquipment3 { get; private set; }

    public ItemCategory ItemCategoryHorseEquipment4 { get; private set; }

    public ItemCategory ItemCategoryHorseEquipment5 { get; private set; }

    public ItemCategory ItemCategoryArrows { get; private set; }

    public DefaultItemCategories(Game game) => this._itemCategories = this.RegisterAll(game).ToArray();

    private List<ItemCategory> RegisterAll(Game game)
    {
      this.ItemCategoryGrain = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("grain"));
      this.ItemCategoryFish = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("fish"));
      this.ItemCategoryMeat = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("meat"));
      this.ItemCategoryCheese = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("cheese"));
      this.ItemCategoryGrape = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("grape"));
      this.ItemCategoryDateFruit = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("date_fruit"));
      this.ItemCategoryOlives = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("olives"));
      this.ItemCategoryButter = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("butter"));
      this.ItemCategoryOil = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("oil"));
      this.ItemCategoryFlax = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("flax"));
      this.ItemCategoryLinen = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("linen"));
      this.ItemCategoryWool = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("wool"));
      this.ItemCategoryCloth = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("cloth"));
      this.ItemCategoryCotton = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("cotton"));
      this.ItemCategoryVelvet = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("velvet"));
      this.ItemCategoryWood = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("hardwood"));
      this.ItemCategoryIron = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("iron"));
      this.ItemCategorySalt = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("salt"));
      this.ItemCategorySilver = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("silver"));
      this.ItemCategoryHides = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("hides"));
      this.ItemCategoryClay = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("clay"));
      this.ItemCategoryBeer = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("beer"));
      this.ItemCategoryWine = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("wine"));
      this.ItemCategoryTools = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("tools"));
      this.ItemCategoryPottery = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("pottery"));
      this.ItemCategoryLeather = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("leather"));
      this.ItemCategoryFur = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("fur"));
      this.ItemCategoryJewelry = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("jewelry"));
      this.ItemCategoryArrows = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("arrows"));
      this.ItemCategorySheep = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("sheep"));
      this.ItemCategoryCow = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("cow"));
      this.ItemCategoryHog = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("hog"));
      this.ItemCategoryPackAnimal = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("sumpter_horse"));
      this.ItemCategoryHorse = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("horse"));
      this.ItemCategoryWarHorse = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("war_horse"));
      this.ItemCategoryHorseEquipment = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("horse_equipment"));
      this.ItemCategoryHorseEquipment2 = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("horse_equipment_2"));
      this.ItemCategoryHorseEquipment3 = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("horse_equipment_3"));
      this.ItemCategoryHorseEquipment4 = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("horse_equipment_4"));
      this.ItemCategoryHorseEquipment5 = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("horse_equipment_5"));
      this.ItemCategoryMeleeWeapons1 = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("melee_weapons"));
      this.ItemCategoryMeleeWeapons2 = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("melee_weapons_2"));
      this.ItemCategoryMeleeWeapons3 = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("melee_weapons_3"));
      this.ItemCategoryMeleeWeapons4 = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("melee_weapons_4"));
      this.ItemCategoryMeleeWeapons5 = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("melee_weapons_5"));
      this.ItemCategoryRangedWeapons1 = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("ranged_weapons"));
      this.ItemCategoryRangedWeapons2 = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("ranged_weapons_2"));
      this.ItemCategoryRangedWeapons3 = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("ranged_weapons_3"));
      this.ItemCategoryRangedWeapons4 = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("ranged_weapons_4"));
      this.ItemCategoryRangedWeapons5 = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("ranged_weapons_5"));
      this.ItemCategoryShield = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("shield"));
      this.ItemCategoryShield2 = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("shield_2"));
      this.ItemCategoryShield3 = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("shield_3"));
      this.ItemCategoryShield4 = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("shield_4"));
      this.ItemCategoryShield5 = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("shield_5"));
      this.ItemCategoryGarment = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("garment"));
      this.ItemCategoryLightArmor = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("light_armor"));
      this.ItemCategoryMediumArmor = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("medium_armor"));
      this.ItemCategoryHeavyArmor = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("heavy_armor"));
      this.ItemCategoryUltraArmor = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("ultra_armor"));
      this.ItemCategoryUnassigned = MBObjectManager.Instance.RegisterPresumedObject<ItemCategory>(new ItemCategory("unassigned"));
      List<ItemCategory> categories = new List<ItemCategory>();
      this.InitializeAll(categories);
      return categories;
    }

    private void InitializeAll(List<ItemCategory> categories)
    {
      categories.Add(this.ItemCategoryGrain.InitializeObject(true, 100, properties: ItemCategory.Property.BonusToFoodStores));
      categories.Add(this.ItemCategoryFish.InitializeObject(true, 32, properties: ItemCategory.Property.BonusToFoodStores, canSubstitute: this.ItemCategoryGrain, substitutionFactor: 0.1f));
      categories.Add(this.ItemCategoryMeat.InitializeObject(true, 36, 12, ItemCategory.Property.BonusToFoodStores, this.ItemCategoryFish, 0.1f));
      categories.Add(this.ItemCategoryCheese.InitializeObject(true, 21, 7, ItemCategory.Property.BonusToFoodStores, this.ItemCategoryGrain, 0.01f));
      categories.Add(this.ItemCategoryButter.InitializeObject(true, 18, 6, ItemCategory.Property.BonusToFoodStores));
      categories.Add(this.ItemCategoryGrape.InitializeObject(true, 9, 3, ItemCategory.Property.BonusToFoodStores, this.ItemCategoryGrain, 0.1f));
      categories.Add(this.ItemCategoryOlives.InitializeObject(true, 9, 3, ItemCategory.Property.BonusToFoodStores, this.ItemCategoryGrain, 0.01f));
      categories.Add(this.ItemCategoryDateFruit.InitializeObject(true, 9, 3, ItemCategory.Property.BonusToFoodStores, this.ItemCategoryGrape, 0.01f));
      categories.Add(this.ItemCategoryOil.InitializeObject(true, 21, 7, ItemCategory.Property.BonusToFoodStores, this.ItemCategoryButter, 0.1f));
      categories.Add(this.ItemCategoryFlax.InitializeObject(true, 12));
      categories.Add(this.ItemCategoryLinen.InitializeObject(true, 30, 10));
      categories.Add(this.ItemCategoryWool.InitializeObject(true, 13));
      categories.Add(this.ItemCategoryCloth.InitializeObject(baseDemand: 12, luxuryDemand: 6));
      categories.Add(this.ItemCategoryCotton.InitializeObject(true, 9, 3));
      categories.Add(this.ItemCategoryVelvet.InitializeObject(true, 12, 6, ItemCategory.Property.BonusToLoyalty));
      categories.Add(this.ItemCategoryWood.InitializeObject(true, 10));
      categories.Add(this.ItemCategoryIron.InitializeObject(true, 5));
      categories.Add(this.ItemCategorySalt.InitializeObject(true, 15, 5, ItemCategory.Property.BonusToTax));
      categories.Add(this.ItemCategorySilver.InitializeObject(true, 10, 5, ItemCategory.Property.BonusToTax));
      categories.Add(this.ItemCategoryHides.InitializeObject(true, 24, 8));
      categories.Add(this.ItemCategoryClay.InitializeObject(true, 20));
      categories.Add(this.ItemCategoryBeer.InitializeObject(true, 42, 14, ItemCategory.Property.BonusToFoodStores));
      categories.Add(this.ItemCategoryWine.InitializeObject(true, 14, 7, ItemCategory.Property.BonusToLoyalty));
      categories.Add(this.ItemCategoryTools.InitializeObject(true, 12, 3, ItemCategory.Property.BonusToProduction));
      categories.Add(this.ItemCategoryPottery.InitializeObject(true, 21, 7));
      categories.Add(this.ItemCategoryLeather.InitializeObject(true, 20, 10));
      categories.Add(this.ItemCategoryFur.InitializeObject(true, 20, 10, ItemCategory.Property.BonusToProsperity));
      categories.Add(this.ItemCategoryJewelry.InitializeObject(true, 28, 14, ItemCategory.Property.BonusToLoyalty));
      categories.Add(this.ItemCategorySheep.InitializeObject(true, 10, isAnimal: true));
      categories.Add(this.ItemCategoryCow.InitializeObject(true, 10, isAnimal: true));
      categories.Add(this.ItemCategoryHog.InitializeObject(true, 8, isAnimal: true));
      categories.Add(this.ItemCategoryPackAnimal.InitializeObject(true, 10, 3, ItemCategory.Property.BonusToProsperity, isAnimal: true));
      categories.Add(this.ItemCategoryHorse.InitializeObject(true, 75, properties: ItemCategory.Property.BonusToProsperity, isAnimal: true));
      categories.Add(this.ItemCategoryWarHorse.InitializeObject(true, 75, 25, ItemCategory.Property.BonusToGarrison, isAnimal: true));
      categories.Add(this.ItemCategoryArrows.InitializeObject(baseDemand: 30, luxuryDemand: 30));
      categories.Add(this.ItemCategoryHorseEquipment.InitializeObject(baseDemand: 9, luxuryDemand: 5));
      categories.Add(this.ItemCategoryHorseEquipment2.InitializeObject(baseDemand: 7, luxuryDemand: 6));
      categories.Add(this.ItemCategoryHorseEquipment3.InitializeObject(baseDemand: 5, luxuryDemand: 7));
      categories.Add(this.ItemCategoryHorseEquipment4.InitializeObject(baseDemand: 5, luxuryDemand: 8));
      categories.Add(this.ItemCategoryHorseEquipment5.InitializeObject(baseDemand: 5, luxuryDemand: 9));
      categories.Add(this.ItemCategoryMeleeWeapons1.InitializeObject(baseDemand: 9, luxuryDemand: 7));
      categories.Add(this.ItemCategoryMeleeWeapons2.InitializeObject(baseDemand: 7, luxuryDemand: 7));
      categories.Add(this.ItemCategoryMeleeWeapons3.InitializeObject(baseDemand: 5, luxuryDemand: 10));
      categories.Add(this.ItemCategoryMeleeWeapons4.InitializeObject(baseDemand: 4, luxuryDemand: 10));
      categories.Add(this.ItemCategoryMeleeWeapons5.InitializeObject(baseDemand: 4, luxuryDemand: 10));
      categories.Add(this.ItemCategoryRangedWeapons1.InitializeObject(baseDemand: 9, luxuryDemand: 7));
      categories.Add(this.ItemCategoryRangedWeapons2.InitializeObject(baseDemand: 7, luxuryDemand: 7));
      categories.Add(this.ItemCategoryRangedWeapons3.InitializeObject(baseDemand: 5, luxuryDemand: 10));
      categories.Add(this.ItemCategoryRangedWeapons4.InitializeObject(baseDemand: 4, luxuryDemand: 10));
      categories.Add(this.ItemCategoryRangedWeapons5.InitializeObject(baseDemand: 4, luxuryDemand: 10));
      categories.Add(this.ItemCategoryShield.InitializeObject(baseDemand: 9, luxuryDemand: 7));
      categories.Add(this.ItemCategoryShield2.InitializeObject(baseDemand: 7, luxuryDemand: 7));
      categories.Add(this.ItemCategoryShield3.InitializeObject(baseDemand: 5, luxuryDemand: 10));
      categories.Add(this.ItemCategoryShield4.InitializeObject(baseDemand: 4, luxuryDemand: 10));
      categories.Add(this.ItemCategoryShield5.InitializeObject(baseDemand: 4, luxuryDemand: 10));
      categories.Add(this.ItemCategoryGarment.InitializeObject(baseDemand: 9, luxuryDemand: 15));
      categories.Add(this.ItemCategoryLightArmor.InitializeObject(baseDemand: 7, luxuryDemand: 16));
      categories.Add(this.ItemCategoryMediumArmor.InitializeObject(baseDemand: 5, luxuryDemand: 17));
      categories.Add(this.ItemCategoryHeavyArmor.InitializeObject(baseDemand: 4, luxuryDemand: 17));
      categories.Add(this.ItemCategoryUltraArmor.InitializeObject(baseDemand: 3, luxuryDemand: 10));
      categories.Add(this.ItemCategoryUnassigned.InitializeObject());
    }
  }
}
