// Decompiled with JetBrains decompiler
// Type: TaleWorlds.Core.GameType
// Assembly: TaleWorlds.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 43F7B45C-9AE1-4715-A37B-2364840F62AF
// Assembly location: E:\SteamLibrary\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Core.dll

using System.Collections.Generic;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.Core
{
  [SaveableClass(10019)]
  public abstract class GameType
  {
    private GameTypeLoadingStates _stepNo;

    protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
    {
    }

    public virtual bool SupportsSaving => false;

    public Game CurrentGame { get; internal set; }

    public MBObjectManager ObjectManager => this.CurrentGame.ObjectManager;

    public GameManagerBase GameManager => this.CurrentGame.GameManager;

    public virtual bool IsInventoryAccessibleAtMission => false;

    public virtual bool IsQuestScreenAccessibleAtMission => false;

    public virtual bool IsCharacterWindowAccessibleAtMission => false;

    public virtual bool IsPartyWindowAccessibleAtMission => false;

    public virtual bool IsKingdomWindowAccessibleAtMission => false;

    public virtual bool IsClanWindowAccessibleAtMission => false;

    public virtual bool IsEncyclopediaWindowAccessibleAtMission => false;

    public virtual bool IsBannerWindowAccessibleAtMission => false;

    public virtual bool IsDevelopment => false;

    public virtual bool IsCoreOnlyGameMode => false;

    public GameType() => this._stepNo = GameTypeLoadingStates.InitializeFirstStep;

    public abstract void OnStateChanged(GameState oldState);

    protected internal abstract void BeforeRegisterTypes(MBObjectManager objectManager);

    protected internal abstract void OnRegisterTypes(MBObjectManager objectManager);

    protected internal abstract void OnInitialize();

    protected abstract void DoLoadingForGameType(
      GameTypeLoadingStates gameTypeLoadingState,
      out GameTypeLoadingStates nextState);

    public bool DoLoadingForGameType()
    {
      bool flag = false;
      GameTypeLoadingStates nextState = GameTypeLoadingStates.None;
      switch (this._stepNo)
      {
        case GameTypeLoadingStates.InitializeFirstStep:
          this.DoLoadingForGameType(GameTypeLoadingStates.InitializeFirstStep, out nextState);
          if (nextState == GameTypeLoadingStates.WaitSecondStep)
          {
            ++this._stepNo;
            break;
          }
          break;
        case GameTypeLoadingStates.WaitSecondStep:
          this.DoLoadingForGameType(GameTypeLoadingStates.WaitSecondStep, out nextState);
          if (nextState == GameTypeLoadingStates.LoadVisualsThirdState)
          {
            ++this._stepNo;
            break;
          }
          break;
        case GameTypeLoadingStates.LoadVisualsThirdState:
          this.DoLoadingForGameType(GameTypeLoadingStates.LoadVisualsThirdState, out nextState);
          if (nextState == GameTypeLoadingStates.PostInitializeFourthState)
          {
            ++this._stepNo;
            break;
          }
          break;
        case GameTypeLoadingStates.PostInitializeFourthState:
          this.DoLoadingForGameType(GameTypeLoadingStates.PostInitializeFourthState, out nextState);
          if (nextState == GameTypeLoadingStates.None)
          {
            ++this._stepNo;
            flag = true;
            break;
          }
          break;
      }
      return flag;
    }

    public abstract void OnDestroy();

    public virtual void OnMissionIsStarting(string missionName, MissionInitializerRecord rec)
    {
    }

    public virtual void InitializeParameters()
    {
    }
  }
}
