// Decompiled with JetBrains decompiler
// Type: TaleWorlds.Core.ItemComponent
// Assembly: TaleWorlds.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 43F7B45C-9AE1-4715-A37B-2364840F62AF
// Assembly location: E:\SteamLibrary\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Core.dll

using System.Collections.Generic;
using System.Xml;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.Core
{
  [SaveableClass(10021)]
  public abstract class ItemComponent : MBObjectBase
  {
    protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
    {
      base.AutoGeneratedInstanceCollectObjects(collectedObjects);
      collectedObjects.Add((object) this.Item);
    }

    internal static object AutoGeneratedGetMemberValueItem(object o) => (object) ((ItemComponent) o).Item;

    [SaveableProperty(100)]
    public ItemObject Item { get; set; }

    public override void Deserialize(MBObjectManager objectManager, XmlNode node) => this.Initialize();

    public abstract ItemComponent GetCopy();

    public virtual void Reset()
    {
    }
  }
}
