// Decompiled with JetBrains decompiler
// Type: TaleWorlds.Core.ManagedParametersEnum
// Assembly: TaleWorlds.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 43F7B45C-9AE1-4715-A37B-2364840F62AF
// Assembly location: E:\SteamLibrary\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Core.dll

namespace TaleWorlds.Core
{
  public enum ManagedParametersEnum
  {
    CampaignMapCenterPointX,
    CampaignMapCenterPointY,
    CampaignMapMaxAllowedDistanceFromCenterPointX,
    CampaignMapMaxAllowedDistanceFromCenterPointY,
    CampaignMapMaxAllowedCameraHeight,
    SiegeTest,
    EnableCampaignTutorials,
    ReducedMouseSensitivityMultiplier,
    RangedAddedElevationForCrosshair,
    MeleeAddedElevationForCrosshair,
    BipedalRadius,
    QuadrupedalRadius,
    BipedalCombatSpeedMinMultiplier,
    BipedalCombatSpeedMaxMultiplier,
    BipedalRangedReadySpeedMultiplier,
    BipedalRangedReloadSpeedMultiplier,
    DamageInterruptAttackThresholdPierce,
    DamageInterruptAttackThresholdCut,
    DamageInterruptAttackThresholdBlunt,
    MakesRearAttackDamageThreshold,
    MissileMinimumDamageToStick,
    BreakableProjectileMinimumBreakSpeed,
    FistFightDamageMultiplier,
    FallDamageMultiplier,
    FallDamageAbsorbtion,
    FallSpeedReductionMultiplierForRiderDamage,
    SwingHitWithArmDamageMultiplier,
    ThrustHitWithArmDamageMultiplier,
    NonTipThrustHitDamageMultiplier,
    SwingCombatSpeedGraphZeroProgressValue,
    SwingCombatSpeedGraphFirstMaximumPoint,
    SwingCombatSpeedGraphSecondMaximumPoint,
    SwingCombatSpeedGraphOneProgressValue,
    OverSwingCombatSpeedGraphZeroProgressValue,
    OverSwingCombatSpeedGraphFirstMaximumPoint,
    OverSwingCombatSpeedGraphSecondMaximumPoint,
    OverSwingCombatSpeedGraphOneProgressValue,
    ThrustCombatSpeedGraphZeroProgressValue,
    ThrustCombatSpeedGraphFirstMaximumPoint,
    ThrustCombatSpeedGraphSecondMaximumPoint,
    ThrustCombatSpeedGraphOneProgressValue,
    StunPeriodAttackerSwing,
    StunPeriodAttackerThrust,
    StunDefendWeaponWeightOffsetShield,
    StunDefendWeaponWeightMultiplierWeaponWeight,
    StunDefendWeaponWeightBonusTwoHanded,
    StunDefendWeaponWeightBonusPolearm,
    StunMomentumTransferFactor,
    StunDefendWeaponWeightParryMultiplier,
    StunDefendWeaponWeightBonusRightStance,
    StunDefendWeaponWeightBonusActiveBlocked,
    StunDefendWeaponWeightBonusChamberBlocked,
    StunPeriodAttackerFriendlyFire,
    StunPeriodMax,
    ProjectileMaxPenetrationSpeed,
    ObjectMinPenetration,
    ObjectMaxPenetration,
    ProjectileMinPenetration,
    ProjectileMaxPenetration,
    RotatingProjectileMinPenetration,
    RotatingProjectileMaxPenetration,
    ShieldRightStanceBlockDamageMultiplier,
    ShieldCorrectSideBlockDamageMultiplier,
    AgentProjectileNormalWeight,
    ProjectileNormalWeight,
    ShieldPenetrationOffset,
    ShieldPenetrationFactor,
    AirFrictionJavelin,
    AirFrictionArrow,
    AirFrictionBullet,
    AirFrictionKnife,
    AirFrictionAxe,
    HeavyAttackMomentumMultiplier,
    ActivateHeroTest,
    Count,
  }
}
