// Decompiled with JetBrains decompiler
// Type: TaleWorlds.Core.PieceData
// Assembly: TaleWorlds.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 43F7B45C-9AE1-4715-A37B-2364840F62AF
// Assembly location: E:\SteamLibrary\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Core.dll

using System.Collections.Generic;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.Core
{
  [SaveableStruct(10042)]
  public struct PieceData
  {
    public static void AutoGeneratedStaticCollectObjectsPieceData(
      object o,
      List<object> collectedObjects)
    {
      ((PieceData) o).AutoGeneratedInstanceCollectObjects(collectedObjects);
    }

    private void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
    {
    }

    public CraftingPiece.PieceTypes PieceType { get; private set; }

    public int Order { get; private set; }

    public PieceData(CraftingPiece.PieceTypes pieceType, int order)
    {
      this.PieceType = pieceType;
      this.Order = order;
    }
  }
}
