// Decompiled with JetBrains decompiler
// Type: TaleWorlds.Core.PlayerGameState
// Assembly: TaleWorlds.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 43F7B45C-9AE1-4715-A37B-2364840F62AF
// Assembly location: E:\SteamLibrary\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Core.dll

using System.Collections.Generic;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.Core
{
  [SaveableClass(10030)]
  public abstract class PlayerGameState : GameState
  {
    private VirtualPlayer _peer;

    protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects) => base.AutoGeneratedInstanceCollectObjects(collectedObjects);

    public VirtualPlayer Peer
    {
      get => this._peer;
      private set => this._peer = value;
    }
  }
}
