// Decompiled with JetBrains decompiler
// Type: TaleWorlds.Core.PropertyObject
// Assembly: TaleWorlds.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 43F7B45C-9AE1-4715-A37B-2364840F62AF
// Assembly location: E:\SteamLibrary\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Core.dll

using System.Collections.Generic;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;

namespace TaleWorlds.Core
{
  public class PropertyObject : MBObjectBase
  {
    private TextObject _name;
    private TextObject _description;

    internal static void AutoGeneratedStaticCollectObjectsPropertyObject(
      object o,
      List<object> collectedObjects)
    {
      ((MBObjectBase) o).AutoGeneratedInstanceCollectObjects(collectedObjects);
    }

    protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects) => base.AutoGeneratedInstanceCollectObjects(collectedObjects);

    public TextObject Name => this._name;

    public TextObject Description => this._description;

    public PropertyObject(string stringId)
      : base(stringId)
    {
    }

    public void Initialize(TextObject name, TextObject description)
    {
      this.Initialize();
      this._name = name;
      this._description = description;
    }
  }
}
