// Decompiled with JetBrains decompiler
// Type: TaleWorlds.Core.TradeItemComponent
// Assembly: TaleWorlds.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 43F7B45C-9AE1-4715-A37B-2364840F62AF
// Assembly location: E:\SteamLibrary\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Core.dll

using System.Collections.Generic;
using System.Xml;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.Core
{
  [SaveableClass(10011)]
  public class TradeItemComponent : ItemComponent
  {
    internal static void AutoGeneratedStaticCollectObjectsTradeItemComponent(
      object o,
      List<object> collectedObjects)
    {
      ((MBObjectBase) o).AutoGeneratedInstanceCollectObjects(collectedObjects);
    }

    protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects) => base.AutoGeneratedInstanceCollectObjects(collectedObjects);

    public int MoraleBonus { get; private set; }

    public TradeItemComponent() => this.MoraleBonus = 0;

    public TradeItemComponent(TradeItemComponent a) => this.MoraleBonus = a.MoraleBonus;

    public override ItemComponent GetCopy() => (ItemComponent) new TradeItemComponent(this);

    public override void Deserialize(MBObjectManager objectManager, XmlNode node)
    {
      this.Initialize();
      this.MoraleBonus = XmlHelper.ReadInt(node, "morale_bonus");
    }
  }
}
