// Decompiled with JetBrains decompiler
// Type: TaleWorlds.Localization.TextProcessor.TokenType
// Assembly: TaleWorlds.Localization, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 26BB3E5A-EB48-4ABD-B2FC-10EF6D7A7285
// Assembly location: E:\SteamLibrary\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Localization.dll

namespace TaleWorlds.Localization.TextProcessor
{
  internal enum TokenType
  {
    NotDefined,
    And,
    Or,
    Not,
    Equals,
    NotEquals,
    GreaterThan,
    LessThan,
    GreaterOrEqual,
    LessOrEqual,
    Comma,
    OpenBraces,
    CloseBraces,
    OpenParenthesis,
    CloseParenthesis,
    OpenBrackets,
    CloseBrackets,
    Number,
    Identifier,
    VariableExpression,
    MarkerOccuranceIdentifier,
    Match,
    ConditionSeperator,
    ConditionFollowUp,
    Seperator,
    ConditionStarter,
    ConditionFinalizer,
    SelectionSeperator,
    SelectionStarter,
    SelectionFinalizer,
    FieldStarter,
    FieldFinalizer,
    SequenceTerminator,
    Text,
    LanguageMarker,
    UnrecognizedTokenError,
    Plus,
    Minus,
    Multiply,
    Divide,
    ArithmeticProduct,
    ArithmeticSum,
    StringExpression,
    SimpleExpression,
    ConditionalExpression,
    SelectionExpression,
    ParenthesisExpression,
    ArrayAccess,
    MultiStatement,
    ComparisonExpression,
    FieldExpression,
    MarkerOccuranceExpression,
    FunctionIdentifier,
    FunctionCall,
    FunctionParam,
    ParameterWithMarkerOccurance,
    QualifiedIdentifier,
    ParameterWithAttribute,
    textId,
  }
}
