// Decompiled with JetBrains decompiler
// Type: TaleWorlds.ObjectSystem.AutoGeneratedSaveManager
// Assembly: TaleWorlds.ObjectSystem, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 525679E6-68C3-48B8-A030-465E146E69EE
// Assembly location: E:\SteamLibrary\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.ObjectSystem.dll

using System.Collections;
using System.Collections.Generic;
using TaleWorlds.Library;
using TaleWorlds.SaveSystem.Definition;

namespace TaleWorlds.ObjectSystem
{
  internal class AutoGeneratedSaveManager : IAutoGeneratedSaveManager
  {
    public void Initialize(DefinitionContext definitionContext)
    {
      TypeDefinition typeDefinition1 = (TypeDefinition) definitionContext.TryGetTypeDefinition((SaveId) new TypeSaveId(10034));
      typeDefinition1.InitializeForAutoGeneration(new CollectObjectsDelegate(MBObjectBase.AutoGeneratedStaticCollectObjectsMBObjectBase));
      typeDefinition1.GetPropertyDefinitionWithId(new MemberTypeId((byte) 2, (short) 1)).InitializeForAutoGeneration(new GetPropertyValueDelegate(MBObjectBase.AutoGeneratedGetMemberValueStringId));
      typeDefinition1.GetPropertyDefinitionWithId(new MemberTypeId((byte) 2, (short) 2)).InitializeForAutoGeneration(new GetPropertyValueDelegate(MBObjectBase.AutoGeneratedGetMemberValueId));
      typeDefinition1.GetPropertyDefinitionWithId(new MemberTypeId((byte) 2, (short) 3)).InitializeForAutoGeneration(new GetPropertyValueDelegate(MBObjectBase.AutoGeneratedGetMemberValueIsRegistered));
      TypeDefinition typeDefinition2 = (TypeDefinition) definitionContext.TryGetTypeDefinition((SaveId) new TypeSaveId(10035));
      typeDefinition2.InitializeForAutoGeneration(new CollectObjectsDelegate(ObsoleteObjectManager.AutoGeneratedStaticCollectObjectsObsoleteObjectManager));
      typeDefinition2.GetFieldDefinitionWithId(new MemberTypeId((byte) 2, (short) 10)).InitializeForAutoGeneration(new GetFieldValueDelegate(ObsoleteObjectManager.AutoGeneratedGetMemberValueObjectTypeRecords));
      typeDefinition2.GetFieldDefinitionWithId(new MemberTypeId((byte) 2, (short) 9)).InitializeForAutoGeneration(new GetFieldValueDelegate(ObsoleteObjectManager.AutoGeneratedGetMemberValue_lastGeneratedId));
      TypeDefinition typeDefinition3 = (TypeDefinition) definitionContext.TryGetTypeDefinition((SaveId) new TypeSaveId(10048));
      SaveId saveId = SaveId.ReadSaveIdFrom((IReader) new StringReader("2 1 0 13001 "));
      ((ContainerDefinition) definitionContext.TryGetTypeDefinition(saveId)).InitializeForAutoGeneration(new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList0), false);
    }

    private static void AutoGeneratedStaticCollectObjectsForList0(
      object o,
      List<object> collectedObjects)
    {
      IList list = (IList) o;
      for (int index = 0; index < list.Count; ++index)
      {
        object obj = list[index];
        collectedObjects.Add(obj);
      }
    }
  }
}
