using System.Reflection;
using System.Runtime.CompilerServices;
using TaleWorlds.Core;
using TaleWorlds.DotNet;

[assembly: Extension]
[assembly: DefineAsEngineStruct(typeof (BodyProperties), "Body_properties")]
[assembly: DefineAsEngineStruct(typeof (MissionInitializerRecord), "Mission_initializer_record")]
[assembly: InternalsVisibleTo("TaleWorlds.MountAndBlade.AutoGenerated")]
[assembly: InternalsVisibleTo("TaleWorlds.Generator.Bannerlord")]
[assembly: DefineAsEngineStruct(typeof (AgentState), "Agent_state")]
[assembly: DefineAsEngineStruct(typeof (MissionMode), "Mission_mode")]
[assembly: AssemblyCompany("TaleWorlds.MountAndBlade")]
[assembly: AssemblyConfiguration("Shipping_Client")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0")]
[assembly: AssemblyProduct("TaleWorlds.MountAndBlade")]
[assembly: AssemblyTitle("TaleWorlds.MountAndBlade")]
[assembly: AssemblyVersion("1.0.0.0")]
