// Decompiled with JetBrains decompiler
// Type: ManagedCallbacks.CallbackManager
// Assembly: TaleWorlds.MountAndBlade.AutoGenerated, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: D02C25D1-9727-49C6-A24A-EE3800F0364C
// Assembly location: E:\SteamLibrary\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.AutoGenerated.dll

using System;
using System.Collections.Generic;
using TaleWorlds.DotNet;
using TaleWorlds.MountAndBlade.AutoGenerated;

namespace ManagedCallbacks
{
  public class CallbackManager : ICallbackManager
  {
    public void Initialize() => CoreCallbacksGenerated.Initialize();

    public Delegate[] GetDelegates() => CoreCallbacksGenerated.Delegates;

    public Dictionary<string, object> GetScriptingInterfaceObjects() => ScriptingInterfaceObjects.GetObjects();

    public void SetFunctionPointer(int id, IntPtr pointer) => ScriptingInterfaceObjects.SetFunctionPointer(id, pointer);

    public void CheckSharedStructureSizes() => SizeChecker.CheckSharedStructureSizes();
  }
}
