// Decompiled with JetBrains decompiler
// Type: ManagedCallbacks.ScriptingInterfaceOfIMBBannerlordTableauManager
// Assembly: TaleWorlds.MountAndBlade.AutoGenerated, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: D02C25D1-9727-49C6-A24A-EE3800F0364C
// Assembly location: E:\SteamLibrary\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.AutoGenerated.dll

using System;
using System.Runtime.InteropServices;
using System.Security;
using System.Text;
using TaleWorlds.DotNet;
using TaleWorlds.MountAndBlade;

namespace ManagedCallbacks
{
  internal class ScriptingInterfaceOfIMBBannerlordTableauManager : IMBBannerlordTableauManager
  {
    private static readonly Encoding _utf8 = Encoding.UTF8;
    public static ScriptingInterfaceOfIMBBannerlordTableauManager.RequestCharacterTableauRenderDelegate call_RequestCharacterTableauRenderDelegate;
    public static ScriptingInterfaceOfIMBBannerlordTableauManager.InitializeCharacterTableauRenderSystemDelegate call_InitializeCharacterTableauRenderSystemDelegate;
    public static ScriptingInterfaceOfIMBBannerlordTableauManager.GetNumberOfPendingTableauRequestsDelegate call_GetNumberOfPendingTableauRequestsDelegate;

    public void RequestCharacterTableauRender(
      int characterCodeId,
      string path,
      UIntPtr poseEntity,
      UIntPtr cameraObject,
      int tableauType)
    {
      byte[] numArray = (byte[]) null;
      if (path != null)
      {
        numArray = CallbackStringBufferManager.StringBuffer0;
        int bytes = ScriptingInterfaceOfIMBBannerlordTableauManager._utf8.GetBytes(path, 0, path.Length, numArray, 0);
        numArray[bytes] = (byte) 0;
      }
      ScriptingInterfaceOfIMBBannerlordTableauManager.call_RequestCharacterTableauRenderDelegate(characterCodeId, numArray, poseEntity, cameraObject, tableauType);
    }

    public void InitializeCharacterTableauRenderSystem() => ScriptingInterfaceOfIMBBannerlordTableauManager.call_InitializeCharacterTableauRenderSystemDelegate();

    public int GetNumberOfPendingTableauRequests() => ScriptingInterfaceOfIMBBannerlordTableauManager.call_GetNumberOfPendingTableauRequestsDelegate();

    [UnmanagedFunctionPointer(CallingConvention.StdCall, CharSet = CharSet.Ansi)]
    [SuppressUnmanagedCodeSecurity]
    [MonoNativeFunctionWrapper]
    public delegate void RequestCharacterTableauRenderDelegate(
      int characterCodeId,
      byte[] path,
      UIntPtr poseEntity,
      UIntPtr cameraObject,
      int tableauType);

    [UnmanagedFunctionPointer(CallingConvention.StdCall, CharSet = CharSet.Ansi)]
    [SuppressUnmanagedCodeSecurity]
    [MonoNativeFunctionWrapper]
    public delegate void InitializeCharacterTableauRenderSystemDelegate();

    [UnmanagedFunctionPointer(CallingConvention.StdCall, CharSet = CharSet.Ansi)]
    [SuppressUnmanagedCodeSecurity]
    [MonoNativeFunctionWrapper]
    public delegate int GetNumberOfPendingTableauRequestsDelegate();
  }
}
