// Decompiled with JetBrains decompiler
// Type: TaleWorlds.Engine.InputSystem.DebugHotKeyCategory
// Assembly: TaleWorlds.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DD7DC4E8-6EB6-4CB8-8DE1-FC78E45F7FE8
// Assembly location: E:\SteamLibrary\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Engine.dll

using TaleWorlds.InputSystem;

namespace TaleWorlds.Engine.InputSystem
{
  public class DebugHotKeyCategory : GameKeyContext
  {
    public const string CategoryId = "Debug";
    public const string LeftMouseButton = "LeftMouseButton";
    public const string RightMouseButton = "RightMouseButton";
    public const string SelectAll = "SelectAll";
    public const string Redo = "Redo";
    public const string Undo = "Undo";
    public const string Copy = "Copy";
    public const string Score = "Score";
    public const string SetOriginToZero = "SetOriginToZero";
    public const string TestEngineCrash = "TestEngineCrash";
    public const string AgentHotkeySwitchRender = "AgentHotkeySwitchRender";
    public const string AgentHotkeySwitchFaceAnimationDebug = "AgentHotkeySwitchFaceAnimationDebug";
    public const string AgentHotkeyCheckCollisionCapsule = "AgentHotkeyCheckCollisionCapsule";
    public const string EngineInterfaceHotkeyWireframe = "EngineInterfaceHotkeyWireframe";
    public const string EngineInterfaceHotkeyWireframe2 = "EngineInterfaceHotkeyWireframe2";
    public const string EngineInterfaceHotkeyTakeScreenShot = "EngineInterfaceHotkeyTakeScreenShot";
    public const string EditingManagerHotkeyCrashReporting = "EditingManagerHotkeyCrashReporting";
    public const string EditingManagerHotkeyEmergencySceneSaving = "EditingManagerHotkeyEmergencySceneSaving";
    public const string EditingManagerHotkeyAssertTestEntityOperations = "EditingManagerHotkeyAssertTestEntityOperations";
    public const string EditingManagerHotkeyUpdateSceneDialog = "EditingManagerHotkeyUpdateSceneDialog";
    public const string EditingManagerHotkeySetTriadToWorld = "EditingManagerHotkeySetTriadToWorld";
    public const string EditingManagerHotkeySetTriadToLocal = "EditingManagerHotkeySetTriadToLocal";
    public const string EditingManagerHotkeySetTriadToScreen = "EditingManagerHotkeySetTriadToScreen";
    public const string EditingManagerHotkeyCameraSmoothMode = "EditingManagerHotkeyCameraSmoothMode";
    public const string EditingManagerHotkeyDisplayNormalsOfSelectedEntities = "EditingManagerHotkeyDisplayNormalsOfSelectedEntities";
    public const string EditingManagerHotkeyChoosePhysicsMaterial = "EditingManagerHotkeyChoosePhysicsMaterial";
    public const string EditingManagerHotkeySwitchObjectsLockedForSelection = "EditingManagerHotkeySwitchObjectsLockedForSelection";
    public const string ApplicationHotkeyAnimationReload = "ApplicationHotkeyAnimationReload";
    public const string ApplicationHotkeyIncreasePingDelay = "ApplicationHotkeyIncreasePingDelay";
    public const string ApplicationHotkeyIncreaseLossRatio = "ApplicationHotkeyIncreaseLossRatio";
    public const string ApplicationHotkeySaveAllContentFilesWithType = "ApplicationHotkeySaveAllContentFilesWithType";
    public const string MissionHotkeySwitchAnimationDebugSystem = "MissionHotkeySwitchAnimationDebugSystem";
    public const string MissionHotkeyAssignMainAgentToDebugAgent = "MissionHotkeyAssignMainAgentToDebugAgent";
    public const string MissionHotkeyUseProgrammerSound = "MissionHotkeyUseProgrammerSound";
    public const string MissionHotkeySetDebugPathStartPos = "MissionHotkeySetDebugPathStartPos";
    public const string MissionHotkeySetDebugPathEndPos = "MissionHotkeySetDebugPathEndPos";
    public const string MissionHotkeyRenderCombatCollisionCapsules = "MissionHotkeyRenderCombatCollisionCapsules";
    public const string ModelviewerHotkeyApplyUpwardsForce = "ModelviewerHotkeyApplyUpwardsForce";
    public const string ModelviewerHotkeyApplyDownwardsForce = "ModelviewerHotkeyApplyDownwardsForce";
    public const string NavigationMeshBuilderHotkeyMakeFourLastVerticesFace = "NavigationMeshBuilderHotkeyMakeFourLastVerticesFace";
    public const string CameraControllerHotkeyMoveForward = "CameraControllerHotkeyMoveForward";
    public const string CameraControllerHotkeyMoveBackward = "CameraControllerHotkeyMoveBackward";
    public const string CameraControllerHotkeyMoveLeft = "CameraControllerHotkeyMoveLeft";
    public const string CameraControllerHotkeyMoveRight = "CameraControllerHotkeyMoveRight";
    public const string CameraControllerHotkeyMoveUpward = "CameraControllerHotkeyMoveUpward";
    public const string CameraControllerHotkeyMoveDownward = "CameraControllerHotkeyMoveDownward";
    public const string CameraControllerHotkeyPenCamera = "CameraControllerHotkeyPenCamera";
    public const string ClothSimulationHotkeyResetAllMeshes = "ClothSimulationHotkeyResetAllMeshes";
    public const string EngineInterfaceHotkeySwitchForwardPhysicxDebugMode = "EngineInterfaceHotkeySwitchForwardPhysicxDebugMode";
    public const string EngineInterfaceHotkeySwitchBackwardPhysicxDebugMode = "EngineInterfaceHotkeySwitchBackwardPhysicxDebugMode";
    public const string EngineInterfaceHotkeyShowPhysicsDebugInfo = "EngineInterfaceHotkeyShowPhysicsDebugInfo";
    public const string EngineInterfaceHotkeyShowProfileModes = "EngineInterfaceHotkeyShowProfileModes";
    public const string EngineInterfaceHotkeyShowDebugInfo = "EngineInterfaceHotkeyShowDebugInfo";
    public const string EngineInterfaceHotkeyDecreaseByTenDrawOneByOneIndex = "EngineInterfaceHotkeyDecreaseByTenDrawOneByOneIndex";
    public const string EngineInterfaceHotkeyIncreaseByTenDrawOneByOneIndex = "EngineInterfaceHotkeyIncreaseByTenDrawOneByOneIndex";
    public const string EngineInterfaceHotkeyDecreaseDrawOneByOneIndex = "EngineInterfaceHotkeyDecreaseDrawOneByOneIndex";
    public const string EngineInterfaceHotkeyIncreaseDrawOneByOneIndex = "EngineInterfaceHotkeyIncreaseDrawOneByOneIndex";
    public const string EngineInterfaceHotkeyForceSetDrawOneByOneIndexMinusone = "EngineInterfaceHotkeyForceSetDrawOneByOneIndexMinusone";
    public const string EngineInterfaceHotkeySetDrawOneByOneIndexMinusone = "EngineInterfaceHotkeySetDrawOneByOneIndexMinusone";
    public const string EngineInterfaceHotkeyReleaseUnusedMemory = "EngineInterfaceHotkeyReleaseUnusedMemory";
    public const string EngineInterfaceHotkeyChangeShaderVisualizationMode = "EngineInterfaceHotkeyChangeShaderVisualizationMode";
    public const string EngineInterfaceHotkeyOnlyRenderDeferredQuad = "EngineInterfaceHotkeyOnlyRenderDeferredQuad";
    public const string EngineInterfaceHotkeyOnlyRenderNonDeferredMeshes = "EngineInterfaceHotkeyOnlyRenderNonDeferredMeshes";
    public const string EngineInterfaceHotkeyChangeAnimationDebugMode = "EngineInterfaceHotkeyChangeAnimationDebugMode";
    public const string EngineInterfaceHotkeyTestAssertReport = "EngineInterfaceHotkeyTestAssertReport";
    public const string EngineInterfaceHotkeyTestCreateBugReportTask = "EngineInterfaceHotkeyTestCreateBugReportTask";
    public const string EngineInterfaceHotkeySlowmotion = "EngineInterfaceHotkeySlowmotion";
    public const string EngineInterfaceHotkeyRecompileShader = "EngineInterfaceHotkeyRecompileShader";
    public const string EngineInterfaceHotkeyToggleConsole = "EngineInterfaceHotkeyToggleConsole";
    public const string EngineInterfaceHotkeyShowConsoleManager = "EngineInterfaceHotkeyShowConsoleManager";
    public const string EngineInterfaceHotkeyShowDebugTools = "EngineInterfaceHotkeyShowDebugTools";
    public const string SceneHotkeyIncreaseEnforcedSkyboxIndex = "SceneHotkeyIncreaseEnforcedSkyboxIndex";
    public const string SceneHotkeyDecreaseEnforcedSkyboxIndex = "SceneHotkeyDecreaseEnforcedSkyboxIndex";
    public const string SceneHotkeyCheckBoundingBoxCorrectness = "SceneHotkeyCheckBoundingBoxCorrectness";
    public const string SceneHotkeyShowNavigationMeshIds = "SceneHotkeyShowNavigationMeshIds";
    public const string SceneHotkeyShowNavigationMeshIdsXray = "SceneHotkeyShowNavigationMeshIdsXray";
    public const string SceneHotkeyShowNavigationMeshIslands = "SceneHotkeyShowNavigationMeshIslands";
    public const string SceneHotkeySetNewCharacterDetailModifier = "SceneHotkeySetNewCharacterDetailModifier";
    public const string SceneHotkeyShowTerrainMaterials = "SceneHotkeyShowTerrainMaterials";
    public const string SceneViewHotkeyTakeHighQualityScreenshot = "SceneViewHotkeyTakeHighQualityScreenshot";
    public const string SoundManagerHotkeyReloadSounds = "SoundManagerHotkeyReloadSounds";
    public const string ReplayEditorHotkeyRenderSounds = "ReplayEditorHotkeyRenderSounds";
    public const string FrameMoveTaskHotkeyUseTelemetryProfiler = "FrameMoveTaskHotkeyUseTelemetryProfiler";
    public const string SkeletonHotkeyActivateDisableAnimationFpsOptimization = "SkeletonHotkeyActivateDisableAnimationFpsOptimization";
    public const string SkeletonHotkeyDisactiveDisableAnimationFpsOptimization = "SkeletonHotkeyDisactiveDisableAnimationFpsOptimization";
    public const string LibraryHotkeyDisableCommitChanges = "LibraryHotkeyDisableCommitChanges";
    public const string Numpad0 = "Numpad0";
    public const string Numpad1 = "Numpad1";
    public const string Numpad3 = "Numpad3";
    public const string Numpad5 = "Numpad5";
    public const string Numpad7 = "Numpad7";
    public const string Numpad9 = "Numpad9";
    public const string D0 = "D0";
    public const string D1 = "D1";
    public const string D2 = "D2";
    public const string D3 = "D3";
    public const string D4 = "D4";
    public const string D5 = "D5";
    public const string D6 = "D6";
    public const string D7 = "D7";
    public const string D8 = "D8";
    public const string D9 = "D9";
    public const string F1 = "F1";
    public const string F2 = "F2";
    public const string F3 = "F3";
    public const string F4 = "F4";
    public const string F5 = "F5";
    public const string F6 = "F6";
    public const string F7 = "F7";
    public const string F8 = "F8";
    public const string F9 = "F9";
    public const string F10 = "F10";
    public const string F11 = "F11";
    public const string Y = "Y";
    public const string A = "A";
    public const string F = "F";
    public const string B = "B";
    public const string N = "N";
    public const string C = "C";
    public const string E = "E";
    public const string J = "J";
    public const string Q = "Q";
    public const string H = "H";
    public const string W = "W";
    public const string S = "S";
    public const string U = "U";
    public const string T = "T";
    public const string K = "K";
    public const string M = "M";
    public const string G = "G";
    public const string D = "D";
    public const string Space = "Space";
    public const string UpArrow = "UpArrow";
    public const string LeftArrow = "LeftArrow";
    public const string DownArrow = "DownArrow";
    public const string RightArrow = "RightArrow";
    public const string NumpadArrowForward = "NumpadArrowForward";
    public const string NumpadArrowBackward = "NumpadArrowBackward";
    public const string NumpadArrowLeft = "NumpadArrowLeft";
    public const string NumpadArrowRight = "NumpadArrowRight";
    public const string SwapToEnemy = "SwapToEnemy";
    public const string ChangeEnemyTeam = "ChangeEnemyTeam";
    public const string Paste = "Paste";
    public const string Cut = "Cut";
    public const string Refresh = "Refresh";
    public const string EnterEditMode = "EnterEditMode";
    public const string FixSkeletons = "FixSkeletons";
    public const string Reset = "Reset";
    public const string AnimationTestControllerHotkeyReequipItems = "AnimationTestControllerHotkeyReequipItems";
    public const string AnimationTestControllerHotkeyUseWeaponTesting = "AnimationTestControllerHotkeyUseWeaponTesting";
    public const string BaseBattleMissionControllerHotkeyBecomePlayer = "BaseBattleMissionControllerHotkeyBecomePlayer";
    public const string BaseBattleMissionControllerHotkeyDrawNavMeshLines = "BaseBattleMissionControllerHotkeyDrawNavMeshLines";
    public const string ModuleHotkeyOpenDebug = "ModuleHotkeyOpenDebug";
    public const string FormationTestMissionControllerHotkeyChargeSide = "FormationTestMissionControllerHotkeyChargeSide";
    public const string FormationTestMissionControllerHotkeyToggleSide = "FormationTestMissionControllerHotkeyToggleSide";
    public const string FormationTestMissionControllerHotkeyToggleFactionBackward = "FormationTestMissionControllerHotkeyToggleFactionBackward";
    public const string FormationTestMissionControllerHotkeyToggleFactionForward = "FormationTestMissionControllerHotkeyToggleFactionForward";
    public const string FormationTestMissionControllerHotkeyToggleTroopForward = "FormationTestMissionControllerHotkeyToggleTroopForward";
    public const string FormationTestMissionControllerHotkeyToggleTroopBackward = "FormationTestMissionControllerHotkeyToggleTroopBackward";
    public const string FormationTestMissionControllerHotkeyIncreaseSpawnCount = "FormationTestMissionControllerHotkeyIncreaseSpawnCount";
    public const string FormationTestMissionControllerHotkeyDecreaseSpawnCount = "FormationTestMissionControllerHotkeyDecreaseSpawnCount";
    public const string FormationTestMissionControllerHotkeySpawnCustom = "FormationTestMissionControllerHotkeySpawnCustom";
    public const string FormationTestMissionControllerHotkeyOrderLooseAndInfantryFormation = "FormationTestMissionControllerHotkeyOrderLooseAndInfantryFormation";
    public const string FormationTestMissionControllerHotkeyOrderScatterAndRangedFormation = "FormationTestMissionControllerHotkeyOrderScatterAndRangedFormation";
    public const string FormationTestMissionControllerHotkeyOrderSkeinAndCavalryFormation = "FormationTestMissionControllerHotkeyOrderSkeinAndCavalryFormation";
    public const string FormationTestMissionControllerHotkeyOrderLineAndHorseArcherFormation = "FormationTestMissionControllerHotkeyOrderLineAndHorseArcherFormation";
    public const string FormationTestMissionControllerHotkeyOrderCircle = "FormationTestMissionControllerHotkeyOrderCircle";
    public const string FormationTestMissionControllerHotkeyOrderColumn = "FormationTestMissionControllerHotkeyOrderColumn";
    public const string FormationTestMissionControllerHotkeyOrderShieldWall = "FormationTestMissionControllerHotkeyOrderShieldWall";
    public const string FormationTestMissionControllerHotkeyOrderSquare = "FormationTestMissionControllerHotkeyOrderSquare";
    public const string AiTestMisisonControllerHotkeySpawnFormation = "AiTestMisisonControllerHotkeySpawnFormation";
    public const string TabbedPanelHotkeyDecreaseSelectedIndex = "TabbedPanelHotkeyDecreaseSelectedIndex";
    public const string TabbedPanelHotkeyIncreaseSelectedIndex = "TabbedPanelHotkeyIncreaseSelectedIndex";
    public const string MissionSingleplayerUiHandlerHotkeyUpdateItems = "MissionSingleplayerUiHandlerHotkeyUpdateItems";
    public const string MissionSingleplayerUiHandlerHotkeyJoinEnemyTeam = "MissionSingleplayerUiHandlerHotkeyJoinEnemyTeam";
    public const string SiegeDeploymentViewHotkeyTeleportMainAgent = "SiegeDeploymentViewHotkeyTeleportMainAgent";
    public const string SiegeDeploymentViewHotkeyFinishDeployment = "SiegeDeploymentViewHotkeyFinishDeployment";
    public const string CraftingScreenHotkeyEnableRuler = "CraftingScreenHotkeyEnableRuler";
    public const string CraftingScreenHotkeyEnableRulerPoint1 = "CraftingScreenHotkeyEnableRulerPoint1";
    public const string CraftingScreenHotkeyEnableRulerPoint2 = "CraftingScreenHotkeyEnableRulerPoint2";
    public const string CraftingScreenHotkeySwitchSelectedPieceMovement = "CraftingScreenHotkeySwitchSelectedPieceMovement";
    public const string CraftingScreenHotkeySetSelectedVariableIndexZero = "CraftingScreenHotkeySetSelectedVariableIndexZero";
    public const string CraftingScreenHotkeySetSelectedVariableIndexOne = "CraftingScreenHotkeySetSelectedVariableIndexOne";
    public const string CraftingScreenHotkeySetSelectedVariableIndexTwo = "CraftingScreenHotkeySetSelectedVariableIndexTwo";
    public const string CraftingScreenHotkeySelectPieceZero = "CraftingScreenHotkeySelectPieceZero";
    public const string CraftingScreenHotkeySelectPieceOne = "CraftingScreenHotkeySelectPieceOne";
    public const string CraftingScreenHotkeySelectPieceTwo = "CraftingScreenHotkeySelectPieceTwo";
    public const string CraftingScreenHotkeySelectPieceThree = "CraftingScreenHotkeySelectPieceThree";
    public const string MbFaceGeneratorScreenHotkeyCamDebugAndAdjustEnabled = "MbFaceGeneratorScreenHotkeyCamDebugAndAdjustEnabled";
    public const string MbFaceGeneratorScreenHotkeyNumpad0 = "MbFaceGeneratorScreenHotkeyNumpad0";
    public const string MbFaceGeneratorScreenHotkeyNumpad1 = "MbFaceGeneratorScreenHotkeyNumpad1";
    public const string MbFaceGeneratorScreenHotkeyNumpad2 = "MbFaceGeneratorScreenHotkeyNumpad2";
    public const string MbFaceGeneratorScreenHotkeyNumpad3 = "MbFaceGeneratorScreenHotkeyNumpad3";
    public const string MbFaceGeneratorScreenHotkeyNumpad4 = "MbFaceGeneratorScreenHotkeyNumpad4";
    public const string MbFaceGeneratorScreenHotkeyNumpad5 = "MbFaceGeneratorScreenHotkeyNumpad5";
    public const string MbFaceGeneratorScreenHotkeyNumpad6 = "MbFaceGeneratorScreenHotkeyNumpad6";
    public const string MbFaceGeneratorScreenHotkeyNumpad7 = "MbFaceGeneratorScreenHotkeyNumpad7";
    public const string MbFaceGeneratorScreenHotkeyNumpad8 = "MbFaceGeneratorScreenHotkeyNumpad8";
    public const string MbFaceGeneratorScreenHotkeyNumpad9 = "MbFaceGeneratorScreenHotkeyNumpad9";
    public const string MbFaceGeneratorScreenHotkeyResetFaceToDefault = "MbFaceGeneratorScreenHotkeyResetFaceToDefault";
    public const string MbFaceGeneratorScreenHotkeySetFaceKeyMax = "MbFaceGeneratorScreenHotkeySetFaceKeyMax";
    public const string MbFaceGeneratorScreenHotkeySetFaceKeyMin = "MbFaceGeneratorScreenHotkeySetFaceKeyMin";
    public const string MbFaceGeneratorScreenHotkeySetCurFaceKeyToMax = "MbFaceGeneratorScreenHotkeySetCurFaceKeyToMax";
    public const string MbFaceGeneratorScreenHotkeySetCurFaceKeyToMin = "MbFaceGeneratorScreenHotkeySetCurFaceKeyToMin";
    public const string SoftwareOcclusionCheckerHotkeySaveOcclusionImage = "SoftwareOcclusionCheckerHotkeySaveOcclusionImage";
    public const string MapScreenHotkeySwitchCampaignTrueSight = "MapScreenHotkeySwitchCampaignTrueSight";
    public const string MapScreenPrintMultiLineText = "MapScreenPrintMultiLineText";
    public const string MapScreenHotkeyShowPos = "MapScreenHotkeyShowPos";
    public const string MapScreenHotkeyOpenEncyclopedia = "MapScreenHotkeyOpenEncyclopedia";
    public const string ReplayCaptureLogicHotkeyRenderWithScreenshot = "ReplayCaptureLogicHotkeyRenderWithScreenshot";
    public const string MissionScreenHotkeyFixCamera = "MissionScreenHotkeyFixCamera";
    public const string MissionScreenHotkeyIncrementArtificialLag = "MissionScreenHotkeyIncrementArtificialLag";
    public const string MissionScreenHotkeyIncrementArtificialLoss = "MissionScreenHotkeyIncrementArtificialLoss";
    public const string MissionScreenHotkeyResetDebugVariables = "MissionScreenHotkeyResetDebugVariables";
    public const string MissionScreenHotkeySwitchCameraSmooth = "MissionScreenHotkeySwitchCameraSmooth";
    public const string MissionScreenHotkeyIncreaseCurrentDiscipline = "MissionScreenHotkeyIncreaseCurrentDiscipline";
    public const string MissionScreenHotkeyDecreaseCurrentDiscipline = "MissionScreenHotkeyDecreaseCurrentDiscipline";
    public const string MissionScreenHotkeyIncreaseFirstFormationWidth = "MissionScreenHotkeyIncreaseFirstFormationWidth";
    public const string MissionScreenHotkeyDecreaseFirstFormationWidth = "MissionScreenHotkeyDecreaseFirstFormationWidth";
    public const string MissionScreenHotkeyExtendedDebugKey = "MissionScreenHotkeyExtendedDebugKey";
    public const string MissionScreenHotkeyShowDebug = "MissionScreenHotkeyShowDebug";
    public const string MissionScreenHotkeyIncreaseTotalUploadLimit = "MissionScreenHotkeyIncreaseTotalUploadLimit";
    public const string MissionScreenIncreaseTotalUploadLimit = "MissionScreenIncreaseTotalUploadLimit";
    public const string MissionScreenHotkeyDecreaseRulerDistanceFromPivot = "MissionScreenHotkeyDecreaseRulerDistanceFromPivot";
    public const string MissionScreenHotkeyIncreaseRulerDistanceFromPivot = "MissionScreenHotkeyIncreaseRulerDistanceFromPivot";
    public const string DebugAgentTeleportMissionControllerHotkeyTeleportMainAgent = "DebugAgentTeleportMissionControllerHotkeyTeleportMainAgent";
    public const string DebugAgentTeleportMissionControllerHotkeyDisableScriptedMovement = "DebugAgentTeleportMissionControllerHotkeyDisableScriptedMovement";
    public const string MissionDebugHandlerHotkeyKillAI = "MissionDebugHandlerHotkeyKillAI";
    public const string MissionDebugHandlerHotkeyKillAttacker = "MissionDebugHandlerHotkeyKillAttacker";
    public const string MissionDebugHandlerHotkeyKillDefender = "MissionDebugHandlerHotkeyKillDefender";
    public const string MissionDebugHandlerHotkeyKillMainAgent = "MissionDebugHandlerHotkeyKillMainAgent";
    public const string MissionDebugHandlerHotkeyAttackingAiAgent = "MissionDebugHandlerHotkeyAttackingAiAgent";
    public const string MissionDebugHandlerHotkeyDefendingAiAgent = "MissionDebugHandlerHotkeyDefendingAiAgent";
    public const string MissionDebugHandlerHotkeyNormalAiAgent = "MissionDebugHandlerHotkeyNormalAiAgent";
    public const string MissionDebugHandlerHotkeyAiAgentSideZero = "MissionDebugHandlerHotkeyAiAgentSideZero";
    public const string MissionDebugHandlerHotkeyAiAgentSideOne = "MissionDebugHandlerHotkeyAiAgentSideOne";
    public const string MissionDebugHandlerHotkeyAiAgentSideTwo = "MissionDebugHandlerHotkeyAiAgentSideTwo";
    public const string MissionDebugHandlerHotkeyAiAgentSideThree = "MissionDebugHandlerHotkeyAiAgentSideThree";
    public const string MissionDebugHandlerHotkeyColorEnemyTeam = "MissionDebugHandlerHotkeyColorEnemyTeam";
    public const string MissionDebugHandlerHotkeyOpenMissionDebug = "MissionDebugHandlerHotkeyOpenMissionDebug";
    public const string UsableMachineAiBaseHotkeyShowMachineUsers = "UsableMachineAiBaseHotkeyShowMachineUsers";
    public const string UsableMachineAiBaseHotkeyRetreatScriptActive = "UsableMachineAiBaseHotkeyRetreatScriptActive";
    public const string UsableMachineAiBaseHotkeyRetreatScriptPassive = "UsableMachineAiBaseHotkeyRetreatScriptPassive";
    public const string CustomCameraMissionViewHotkeyIncreaseCustomCameraIndex = "CustomCameraMissionViewHotkeyIncreaseCustomCameraIndex";
    public const string DebugSiegeBehaviourHotkeyAimAtBallistas = "DebugSiegeBehaviourHotkeyAimAtBallistas";
    public const string DebugSiegeBehaviourHotkeyAimAtMangonels = "DebugSiegeBehaviourHotkeyAimAtMangonels";
    public const string DebugSiegeBehaviourHotkeyAimAtBattlements = "DebugSiegeBehaviourHotkeyAimAtBattlements";
    public const string DebugSiegeBehaviourHotkeyAimAtNone = "DebugSiegeBehaviourHotkeyAimAtNone";
    public const string DebugSiegeBehaviourHotkeyAimAtNone2 = "DebugSiegeBehaviourHotkeyAimAtNone2";
    public const string DebugSiegeBehaviourHotkeyTargetDebugActive = "DebugSiegeBehaviourHotkeyTargetDebugActive";
    public const string DebugSiegeBehaviourHotkeyTargetDebugDisactive = "DebugSiegeBehaviourHotkeyTargetDebugDisactive";
    public const string DebugSiegeBehaviourHotkeyAimAtRam = "DebugSiegeBehaviourHotkeyAimAtRam";
    public const string DebugSiegeBehaviourHotkeyAimAtSt = "DebugSiegeBehaviourHotkeyAimAtSt";
    public const string DebugSiegeBehaviourHotkeyAimAtBallistas2 = "DebugSiegeBehaviourHotkeyAimAtBallistas2";
    public const string DebugSiegeBehaviourHotkeyAimAtMangonels2 = "DebugSiegeBehaviourHotkeyAimAtMangonels2";
    public const string DebugNetworkEventStatisticsHotkeyClear = "DebugNetworkEventStatisticsHotkeyClear";
    public const string DebugNetworkEventStatisticsHotkeyDumpDataAndClear = "DebugNetworkEventStatisticsHotkeyDumpDataAndClear";
    public const string DebugNetworkEventStatisticsHotkeyDumpData = "DebugNetworkEventStatisticsHotkeyDumpData";
    public const string DebugNetworkEventStatisticsHotkeyClearReplicationData = "DebugNetworkEventStatisticsHotkeyClearReplicationData";
    public const string DebugNetworkEventStatisticsHotkeyDumpReplicationData = "DebugNetworkEventStatisticsHotkeyDumpReplicationData";
    public const string DebugNetworkEventStatisticsHotkeyDumpAndClearReplicationData = "DebugNetworkEventStatisticsHotkeyDumpAndClearReplicationData";
    public const string DebugNetworkEventStatisticsHotkeyToggleActive = "DebugNetworkEventStatisticsHotkeyToggleActive";
    public const string AiSelectDebugAgent1 = "AiSelectDebugAgent1";
    public const string AiSelectDebugAgent2 = "AiSelectDebugAgent2";
    public const string AiClearDebugAgents = "AiClearDebugAgents";
    public const string DebugCustomBattlePredefinedSettings1 = "DebugCustomBattlePredefinedSettings1";
    public const string CraftingScreenResetVariable = "CraftingScreenResetVariable";
    public const string DisableParallelSettlementPositionUpdate = "DisableParallelSettlementPositionUpdate";
    public const string OpenUIEditor = "OpenUIEditor";
    public const string ToggleUI = "ToggleUI";
    public const string LeaveWhileInConversation = "LeaveWhileInConversation";
    public const string ShowHighlightsSummary = "ShowHighlightsSummary";
    public const string ResetMusicParameters = "ResetMusicParameters";
    public const string UIExtendedDebugKey = "UIExtendedDebugKey";
    public const string FaceGeneratorExtendedDebugKey = "FaceGeneratorExtendedDebugKey";
    public const string FormationTestMissionExtendedDebugKey = "FormationTestMissionExtendedDebugKey";
    public const string FormationTestMissionExtendedDebugKey2 = "FormationTestMissionExtendedDebugKey2";

    public DebugHotKeyCategory()
      : base("Debug", 0)
    {
      this.RegisterDebugHotkey(nameof (CraftingScreenResetVariable), InputKey.Home, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (LeftMouseButton), InputKey.LeftMouseButton, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (RightMouseButton), InputKey.RightMouseButton, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (Score), InputKey.O, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (Copy), InputKey.C, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (Numpad0), InputKey.Numpad0, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (Numpad1), InputKey.Numpad1, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (NumpadArrowBackward), InputKey.Numpad2, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (Numpad3), InputKey.Numpad3, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (NumpadArrowLeft), InputKey.Numpad4, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (Numpad5), InputKey.Numpad5, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (NumpadArrowRight), InputKey.Numpad6, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (Numpad7), InputKey.Numpad7, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (NumpadArrowForward), InputKey.Numpad8, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (Numpad9), InputKey.Numpad9, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (Reset), InputKey.R, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (SiegeDeploymentViewHotkeyFinishDeployment), InputKey.P, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MapScreenHotkeyShowPos), InputKey.T, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (Y), InputKey.Y, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (E), InputKey.E, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (J), InputKey.J, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (H), InputKey.H, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (F1), InputKey.F1, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (F2), InputKey.F2, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (F3), InputKey.F3, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (F4), InputKey.F4, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (F5), InputKey.F5, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (F6), InputKey.F6, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (F7), InputKey.F7, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (F8), InputKey.F8, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (F9), InputKey.F9, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (F10), InputKey.F10, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (F11), InputKey.F11, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MissionScreenHotkeyShowDebug), InputKey.F12, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (ToggleUI), InputKey.F10, HotKey.Modifiers.Alt | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (MissionScreenHotkeyExtendedDebugKey), InputKey.K, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (DebugAgentTeleportMissionControllerHotkeyDisableScriptedMovement), InputKey.Home, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (EngineInterfaceHotkeyTakeScreenShot), InputKey.Insert, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MissionScreenIncreaseTotalUploadLimit), InputKey.PageDown, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MissionScreenHotkeyIncreaseTotalUploadLimit), InputKey.PageUp, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MissionScreenHotkeyDecreaseRulerDistanceFromPivot), InputKey.PageDown, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MissionScreenHotkeyIncreaseRulerDistanceFromPivot), InputKey.PageUp, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MissionHotkeySetDebugPathEndPos), InputKey.X, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MissionHotkeyRenderCombatCollisionCapsules), InputKey.V, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (T), InputKey.T, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (K), InputKey.K, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (U), InputKey.U, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MissionHotkeySetDebugPathStartPos), InputKey.Z, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (A), InputKey.A, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (B), InputKey.B, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (C), InputKey.C, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (AiTestMisisonControllerHotkeySpawnFormation), InputKey.M, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (N), InputKey.N, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (Q), InputKey.Q, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (Space), InputKey.Space, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (F), InputKey.F, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (W), InputKey.W, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (S), InputKey.S, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (D), InputKey.D, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (UpArrow), InputKey.Up, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (LeftArrow), InputKey.Left, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (RightArrow), InputKey.Right, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (DownArrow), InputKey.Down, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (D0), InputKey.D0, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (D1), InputKey.D1, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (D2), InputKey.D2, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (D3), InputKey.D3, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (D4), InputKey.D4, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (D5), InputKey.D5, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (D6), InputKey.D6, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (D7), InputKey.D7, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (D8), InputKey.D8, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (D9), InputKey.D9, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (ChangeEnemyTeam), InputKey.NumpadSlash, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (AnimationTestControllerHotkeyReequipItems), InputKey.J, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (AnimationTestControllerHotkeyUseWeaponTesting), InputKey.L, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (SwapToEnemy), InputKey.E, HotKey.Modifiers.Shift | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (BaseBattleMissionControllerHotkeyBecomePlayer), InputKey.P, HotKey.Modifiers.Shift | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (BaseBattleMissionControllerHotkeyDrawNavMeshLines), InputKey.N, HotKey.Modifiers.Shift);
      this.RegisterDebugHotkey(nameof (ModuleHotkeyOpenDebug), InputKey.D, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (TabbedPanelHotkeyDecreaseSelectedIndex), InputKey.Tab, HotKey.Modifiers.Shift | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (TabbedPanelHotkeyIncreaseSelectedIndex), InputKey.Tab, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (Paste), InputKey.V, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (Cut), InputKey.X, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (MissionSingleplayerUiHandlerHotkeyUpdateItems), InputKey.U, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (MissionSingleplayerUiHandlerHotkeyJoinEnemyTeam), InputKey.Numpad9, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (MapScreenHotkeySwitchCampaignTrueSight), InputKey.T, HotKey.Modifiers.Alt | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (SiegeDeploymentViewHotkeyTeleportMainAgent), InputKey.LeftMouseButton, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (SoftwareOcclusionCheckerHotkeySaveOcclusionImage), InputKey.NumpadSlash, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (UIExtendedDebugKey), InputKey.G, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MapScreenHotkeyOpenEncyclopedia), InputKey.E, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MbFaceGeneratorScreenHotkeyCamDebugAndAdjustEnabled), InputKey.L, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (FaceGeneratorExtendedDebugKey), InputKey.F, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MbFaceGeneratorScreenHotkeyNumpad0), InputKey.Numpad0, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MbFaceGeneratorScreenHotkeyNumpad1), InputKey.Numpad1, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MbFaceGeneratorScreenHotkeyNumpad2), InputKey.Numpad2, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MbFaceGeneratorScreenHotkeyNumpad3), InputKey.Numpad3, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MbFaceGeneratorScreenHotkeyNumpad4), InputKey.Numpad4, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MbFaceGeneratorScreenHotkeyNumpad5), InputKey.Numpad5, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MbFaceGeneratorScreenHotkeyNumpad6), InputKey.Numpad6, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MbFaceGeneratorScreenHotkeyNumpad7), InputKey.Numpad7, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MbFaceGeneratorScreenHotkeyNumpad8), InputKey.Numpad8, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MbFaceGeneratorScreenHotkeyNumpad9), InputKey.Numpad9, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (MbFaceGeneratorScreenHotkeyResetFaceToDefault), InputKey.D0, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (FormationTestMissionExtendedDebugKey), InputKey.Period, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (FormationTestMissionControllerHotkeyChargeSide), InputKey.Numpad9, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (FormationTestMissionControllerHotkeyToggleSide), InputKey.NumpadPeriod, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (FormationTestMissionControllerHotkeyToggleFactionBackward), InputKey.Numpad1, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (FormationTestMissionControllerHotkeyToggleFactionForward), InputKey.Numpad2, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (FormationTestMissionControllerHotkeyToggleTroopForward), InputKey.Numpad5, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (FormationTestMissionControllerHotkeyToggleTroopBackward), InputKey.Numpad4, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (FormationTestMissionControllerHotkeyIncreaseSpawnCount), InputKey.Numpad8, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (FormationTestMissionControllerHotkeyDecreaseSpawnCount), InputKey.Numpad7, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (FormationTestMissionControllerHotkeySpawnCustom), InputKey.Numpad0, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (FormationTestMissionControllerHotkeyOrderLooseAndInfantryFormation), InputKey.Numpad1, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (FormationTestMissionControllerHotkeyOrderScatterAndRangedFormation), InputKey.Numpad2, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (FormationTestMissionControllerHotkeyOrderSkeinAndCavalryFormation), InputKey.Numpad3, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (FormationTestMissionControllerHotkeyOrderLineAndHorseArcherFormation), InputKey.Numpad4, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (FormationTestMissionExtendedDebugKey2), InputKey.S, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (FormationTestMissionControllerHotkeyOrderCircle), InputKey.Numpad5, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (FormationTestMissionControllerHotkeyOrderColumn), InputKey.Numpad6, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (FormationTestMissionControllerHotkeyOrderShieldWall), InputKey.Numpad7, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (FormationTestMissionControllerHotkeyOrderSquare), InputKey.Numpad8, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (CustomCameraMissionViewHotkeyIncreaseCustomCameraIndex), InputKey.Y, HotKey.Modifiers.Alt | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (CraftingScreenHotkeyEnableRuler), InputKey.R, HotKey.Modifiers.Shift | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (CraftingScreenHotkeyEnableRulerPoint1), InputKey.D1, HotKey.Modifiers.Shift | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (CraftingScreenHotkeyEnableRulerPoint2), InputKey.D2, HotKey.Modifiers.Shift | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (CraftingScreenHotkeySwitchSelectedPieceMovement), InputKey.M, HotKey.Modifiers.Shift | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (CraftingScreenHotkeySetSelectedVariableIndexZero), InputKey.Numpad1, HotKey.Modifiers.Shift | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (CraftingScreenHotkeySetSelectedVariableIndexOne), InputKey.Numpad2, HotKey.Modifiers.Shift | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (CraftingScreenHotkeySetSelectedVariableIndexTwo), InputKey.Numpad3, HotKey.Modifiers.Shift | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (CraftingScreenHotkeySelectPieceZero), InputKey.D1, HotKey.Modifiers.Alt | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (CraftingScreenHotkeySelectPieceOne), InputKey.D2, HotKey.Modifiers.Alt | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (CraftingScreenHotkeySelectPieceTwo), InputKey.D3, HotKey.Modifiers.Alt | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (CraftingScreenHotkeySelectPieceThree), InputKey.D4, HotKey.Modifiers.Alt | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (MbFaceGeneratorScreenHotkeySetFaceKeyMin), InputKey.D1, HotKey.Modifiers.Shift);
      this.RegisterDebugHotkey(nameof (MbFaceGeneratorScreenHotkeySetFaceKeyMax), InputKey.D2, HotKey.Modifiers.Shift);
      this.RegisterDebugHotkey(nameof (Refresh), InputKey.R, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (MbFaceGeneratorScreenHotkeySetCurFaceKeyToMin), InputKey.D1, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (MbFaceGeneratorScreenHotkeySetCurFaceKeyToMax), InputKey.D2, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (MissionScreenHotkeyFixCamera), InputKey.Home, HotKey.Modifiers.Alt | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (ReplayCaptureLogicHotkeyRenderWithScreenshot), InputKey.Numpad1, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (EnterEditMode), InputKey.E, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (MissionScreenHotkeyIncrementArtificialLag), InputKey.L, HotKey.Modifiers.Shift);
      this.RegisterDebugHotkey(nameof (MissionScreenHotkeyIncrementArtificialLoss), InputKey.J, HotKey.Modifiers.Shift);
      this.RegisterDebugHotkey(nameof (MissionScreenHotkeyResetDebugVariables), InputKey.X, HotKey.Modifiers.Shift | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (FixSkeletons), InputKey.K, HotKey.Modifiers.Shift | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (MissionScreenHotkeySwitchCameraSmooth), InputKey.S, HotKey.Modifiers.Alt | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (MissionScreenHotkeyIncreaseCurrentDiscipline), InputKey.D, HotKey.Modifiers.Alt | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (MissionScreenHotkeyDecreaseCurrentDiscipline), InputKey.D, HotKey.Modifiers.Shift | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (DebugAgentTeleportMissionControllerHotkeyTeleportMainAgent), InputKey.MiddleMouseButton, HotKey.Modifiers.Alt | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (MissionDebugHandlerHotkeyKillAI), InputKey.Numpad1, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (MissionDebugHandlerHotkeyOpenMissionDebug), InputKey.PageUp, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (MissionDebugHandlerHotkeyKillDefender), InputKey.Numpad2, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (MissionDebugHandlerHotkeyKillAttacker), InputKey.Numpad3, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (MissionDebugHandlerHotkeyKillMainAgent), InputKey.Numpad9, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (MissionDebugHandlerHotkeyAttackingAiAgent), InputKey.LeftMouseButton, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (MissionDebugHandlerHotkeyDefendingAiAgent), InputKey.RightMouseButton, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (MissionDebugHandlerHotkeyNormalAiAgent), InputKey.MiddleMouseButton, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (MissionDebugHandlerHotkeyAiAgentSideZero), InputKey.Left, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (MissionDebugHandlerHotkeyAiAgentSideOne), InputKey.Right, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (MissionDebugHandlerHotkeyAiAgentSideTwo), InputKey.Up, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (MissionDebugHandlerHotkeyAiAgentSideThree), InputKey.Down, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (UsableMachineAiBaseHotkeyShowMachineUsers), InputKey.Up, HotKey.Modifiers.Alt | HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (UsableMachineAiBaseHotkeyRetreatScriptActive), InputKey.Numpad7, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (UsableMachineAiBaseHotkeyRetreatScriptPassive), InputKey.Numpad7, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (MissionDebugHandlerHotkeyColorEnemyTeam), InputKey.NumpadMultiply, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (DebugSiegeBehaviourHotkeyAimAtBallistas), InputKey.Numpad3, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (DebugSiegeBehaviourHotkeyAimAtBallistas2), InputKey.Numpad3, HotKey.Modifiers.Shift);
      this.RegisterDebugHotkey(nameof (DebugSiegeBehaviourHotkeyAimAtMangonels), InputKey.Numpad4, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (DebugSiegeBehaviourHotkeyAimAtMangonels2), InputKey.Numpad4, HotKey.Modifiers.Shift);
      this.RegisterDebugHotkey(nameof (DebugSiegeBehaviourHotkeyAimAtBattlements), InputKey.Numpad5, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (DebugSiegeBehaviourHotkeyTargetDebugActive), InputKey.Numpad8, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (DebugSiegeBehaviourHotkeyTargetDebugDisactive), InputKey.Numpad8, HotKey.Modifiers.Shift);
      this.RegisterDebugHotkey(nameof (DebugSiegeBehaviourHotkeyAimAtNone), InputKey.Numpad0, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (DebugSiegeBehaviourHotkeyAimAtNone2), InputKey.Numpad0, HotKey.Modifiers.Shift);
      this.RegisterDebugHotkey(nameof (DebugSiegeBehaviourHotkeyAimAtRam), InputKey.Numpad1, HotKey.Modifiers.Shift);
      this.RegisterDebugHotkey(nameof (DebugSiegeBehaviourHotkeyAimAtSt), InputKey.Numpad2, HotKey.Modifiers.Shift);
      this.RegisterDebugHotkey(nameof (DebugNetworkEventStatisticsHotkeyToggleActive), InputKey.F6, HotKey.Modifiers.Shift | HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (DebugNetworkEventStatisticsHotkeyClear), InputKey.M, HotKey.Modifiers.Shift | HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (DebugNetworkEventStatisticsHotkeyDumpDataAndClear), InputKey.N, HotKey.Modifiers.Shift | HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (DebugNetworkEventStatisticsHotkeyDumpData), InputKey.J, HotKey.Modifiers.Shift | HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (DebugNetworkEventStatisticsHotkeyClearReplicationData), InputKey.V, HotKey.Modifiers.Shift | HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (DebugNetworkEventStatisticsHotkeyDumpReplicationData), InputKey.C, HotKey.Modifiers.Shift | HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (DebugNetworkEventStatisticsHotkeyDumpAndClearReplicationData), InputKey.B, HotKey.Modifiers.Shift | HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (DebugCustomBattlePredefinedSettings1), InputKey.F1, HotKey.Modifiers.Control);
      this.RegisterDebugHotkey(nameof (DisableParallelSettlementPositionUpdate), InputKey.M, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (OpenUIEditor), InputKey.U, HotKey.Modifiers.Alt);
      this.RegisterDebugHotkey(nameof (MapScreenPrintMultiLineText), InputKey.Minus, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (LeaveWhileInConversation), InputKey.Tab, HotKey.Modifiers.None);
      this.RegisterDebugHotkey(nameof (ShowHighlightsSummary), InputKey.H, HotKey.Modifiers.Shift);
      this.RegisterDebugHotkey(nameof (ResetMusicParameters), InputKey.R, HotKey.Modifiers.Shift | HotKey.Modifiers.Alt | HotKey.Modifiers.Control);
    }

    private void RegisterDebugHotkey(
      string id,
      InputKey hotkeyKey,
      HotKey.Modifiers modifiers,
      HotKey.Modifiers negativeModifiers = HotKey.Modifiers.None)
    {
      this.RegisterHotKey(new HotKey(id, "Debug", hotkeyKey, modifiers, negativeModifiers));
    }
  }
}
